### PR TITLE
Add new GPU resource to ND

### PR DESCRIPTION
**Pull request by khurtado**
Notre Dame CAML GPU cluster

### CODE REVIEW

**Comment by djw8605** [comment]
Hi,

The current site is ND - CMS_GPU.   Could you also add another resource with that name, even if it's not used in the future?  That would allow Accounting to understand that resource.

-Derek

**Comment by matyasselmeci** [comment]
Hi Kenyi,
What's running on the host you're registering? `HeadNode` is not a valid service type, so I'm trying to figure out what it should be.

**Comment by khurtado** [comment]
Hi Matyas,

It's a condor submit node. There is an OSG Hosted CE submitting to that node. What should I put instead?

**Comment by matyasselmeci** [comment]
I don't think we register those; we just register the hosted CE. @djw8605, do we want to start keeping track of those too? In that case, we should probably create a new service type since none of the others seem to apply.

**Comment by djw8605** [comment]
If this is a hosted-ce site, then only the hosted-ce should be registered.  We haven't registered login nodes in the past.

**Comment by khurtado** [comment]
Ok, I just changed this to CE and put `hosted-ce35.grid.uchicago.edu` instead. I also added "ND - CMS_GPU" with a made-up CE FQDN, but as non-active resource to take care of the current accounting name entry.

**Pull request merged**
