### PR TITLE
Adding new Villanova University site and hosted ce

### PR DESCRIPTION
**Pull request by coldbeer101**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Is this site joining the production pool or the testing (ITB) pool? If it's the production pool, then the resource group yaml file shouldn't have -ITB in the name. If it's the ITB pool, the resource group should have `Production: false` instead of `Production: true`.

**Comment by coldbeer101** [comment]
oh I just copied what the user put in the ticket ( https://support.opensciencegrid.org/a/tickets/67909 ):
Facility:                             Villanova University
Site:                                   AUGIE UC
Resource Group:             VU-AUGIE-ITB
Resource:                         VU-AUGIE-CE (Hosted by OSG)

I can change that though since we use ITB. Ill remove it.

**Comment by coldbeer101** [comment]
ok updated the name now.

**Comment by matyasselmeci** [comment]
You'll also need to add a `topology/Villanova University/FACILITY.yaml` file with these contents:
```
ID: 10192
```

**Comment by coldbeer101** [comment]
done

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
