### PR TITLE
add check for unique FQDNs (SOFTWARE-3374)

### PR DESCRIPTION
**Pull request by edquist**
not currently enforced.

### CODE REVIEW

**Comment by edquist** [comment]
I added the check to the `verify_resources.py` script.

The new output is:

```
*** FQDNs must be unique across the OSG topology
FQDN 'cms25.physics.ucsb.edu' mentioned for multiple resources:
 - UCSB_CE (UC Santa Barbara/ucsb-hep/ucsb-cms.yaml)
 - UCSB_SE (UC Santa Barbara/ucsb-hep/ucsb-cms.yaml)
FQDN 'cmssw3.princeton.edu' mentioned for multiple resources:
 - Princeton_ICSE_T3_CMS_SE (Princeton University/Princeton_ICSE/Princeton_ICSE_T3_CMS.yaml)
 - T3_US_Princeton_ICSE (Princeton University/Princeton_ICSE/Princeton_ICSE_T3_CMS.yaml)
FQDN 'lutse1.lunet.edu' mentioned for multiple resources:
 - Lucille-squid (Langston University/LUCCRE/LUCILLE.yaml)
 - Lucille_SE (Langston University/LUCCRE/LUCILLE.yaml)
FQDN 'net2.rc.fas.harvard.edu' mentioned for multiple resources:
 - HU_ATLAS_Tier2 (Harvard University/Harvard University/HU_ATLAS_Tier2.yaml)
 - NET2_HU (Harvard University/Harvard University/HU_ATLAS_Tier2.yaml)
 - net2.rc.fas.harvard.edu-squid (Harvard University/Harvard University/HU_ATLAS_Tier2.yaml)
FQDN 'osg-ce.hpc.osc.edu' mentioned for multiple resources:
 - OSC_OSG_CE (Ohio Supercomputer Center/OSC/OSC_OSG.yaml)
 - OSC_OSG_squid (Ohio Supercomputer Center/OSC/OSC_OSG.yaml)
FQDN 'osggridftp02.slac.stanford.edu' mentioned for multiple resources:
 - SLAC-ATLAS-T3_GRIDFTP (Stanford University/SLAC/WT2.yaml)
 - WT2_SE (Stanford University/SLAC/WT2.yaml)
FQDN 'perfsonar.unl.edu' mentioned for multiple resources:
 - US-Nebraska BW (Test) (University of Nebraska/Nebraska-CMS/Nebraska.yaml)
 - US-Nebraska LT (Test) (University of Nebraska/Nebraska-CMS/Nebraska.yaml)
FQDN 'perfsonar1.ihepa.ufl.edu' mentioned for multiple resources:
 - perfSONAR_UF LAT (University of Florida/UF CMS Tier2/UFlorida-PG.yaml)
 - T2_Florida_LT (University of Florida/UF HPC/UFlorida-HPC.yaml)
FQDN 'perfsonar2.ihepa.ufl.edu' mentioned for multiple resources:
 - perfSONAR_UF BW (University of Florida/UF CMS Tier2/UFlorida-PG.yaml)
 - T2_Florida_BW (University of Florida/UF HPC/UFlorida-HPC.yaml)
FQDN 'ps-development.bnl.gov' mentioned for multiple resources:
 - BNL-ps-testbed (Brookhaven National Laboratory/Brookhaven ATLAS Tier1/BNL-ATLAS-ITB.yaml)
 - ps-development (Brookhaven National Laboratory/Brookhaven ATLAS Tier1/BNL-ATLAS.yaml)
FQDN 'psonartest1.fnal.gov' mentioned for multiple resources:
 - FNAL NRTB PerfSONAR Bandwidth (Fermi National Accelerator Laboratory/FNAL USCMS Tier1/USCMS-FNAL-WC1.yaml)
 - USCMS PerfSonar IPV6 Test (Fermi National Accelerator Laboratory/FNAL USCMS Tier1/USCMS-FNAL-WC1.yaml)
FQDN 'psuta01.atlas-swt2.org' mentioned for multiple resources:
 - SWT2_CPB_perfSONAR_latency (University of Texas Arlington/SWT2 ATLAS UTA/SWT2_CPB.yaml)
 - UTA_SWT2_perfSONAR_latency (University of Texas Arlington/SWT2 ATLAS UTA/UTA_SWT2.yaml)
FQDN 'psuta02.atlas-swt2.org' mentioned for multiple resources:
 - SWT2_CPB_perfSONAR_bandwidth (University of Texas Arlington/SWT2 ATLAS UTA/SWT2_CPB.yaml)
 - UTA_SWT2_perfSONAR_bandwidth (University of Texas Arlington/SWT2 ATLAS UTA/UTA_SWT2.yaml)
FQDN 'rccf-osg.ci-connect.net' mentioned for multiple resources:
 - Clemson-Connect (Clemson University/Clemson IT/Clemson-Palmetto.yaml)
 - SU-OSG-CONNECT (Syracuse University/SU ITS/SU-ITS.yaml)
FQDN 'sbahead.physics.sunysb.edu' mentioned for multiple resources:
 - SBU_ATLAS_GRIDFTP1 (Stony Brook University/SBU Atlas Tier3/SBU_Tier3.yaml)
 - SBU_T3_Squid (Stony Brook University/SBU Atlas Tier3/SBU_Tier3.yaml)
FQDN 'se2.accre.vanderbilt.edu' mentioned for multiple resources:
 - Vanderbilt_EC2_CE (Vanderbilt University/Vanderbilt_EC2/Vanderbilt_EC2.yaml)
 - Vanderbilt_EC2_SE (Vanderbilt University/Vanderbilt_EC2/Vanderbilt_EC2.yaml)
FQDN 't3serv007.mit.edu' mentioned for multiple resources:
 - MIT_CMS_T3-CE1 (Massachusetts Institute of Technology/MIT CMS T3/MIT_CMS_T3.yaml)
 - MIT_CampusFactory (Massachusetts Institute of Technology/MIT CMS/MIT_CMS.yaml)
FQDN 'xenia.nevis.columbia.edu' mentioned for multiple resources:
 - Nevis cvmfs squid (Columbia University_Nevis Labs/Nevis/Nevis.yaml)
 - Nevis_gridftp (Columbia University_Nevis Labs/Nevis/Nevis.yaml)
205 Resource Group files processed.
19 warning(s) encountered.
```

**Comment by bbockelm** [comment]
Oh, that's actually much better than I had expected!

@brianhlin - I'd strongly like to do a ticket flood asking admins for permission to merge resources together.

- perfSonar merging should be coordinated with @ShawnMcKee 
- Squid merging should be coordinated with @DrDaveD (as there may be some WLCG registration aspect I don't know about).
- ATLAS changes should be coordinated with Rob Gardner
- CMS changes should be coordinated with James Letts
- I spot one OSG Connect service @sthapa could help with.

We probably want to try to preserve the CE and SE names where possible (meaning to make the squid registrations disappear.  Squid should simply be another service running on the CE resource).

If we could get the list of duplicates down to 0, I'd love to have this test be mandatory.

**Comment by edquist** [comment]
@brianhlin, wanna give this a review so we can merge?

And we can make it the check mandatory later once admins clean up the duplicates.

Or did you want to leave this test out completely until then?

**Comment by edquist** [comment]
> Can you compare the warning list vs what I have in SOFTWARE-3373?

Yup, the set of FQDNs with duplicates and their counts are identical between what's shown above and what's in SOFTWARE-3373.

**Comment by brianhlin** [comment]
Heh. Are there any warnings that you excluded in your output [here](https://github.com/opensciencegrid/topology/pull/154#issuecomment-410093252)? Because I count 18 FQDNs and it says there are 19 warnings :)

**Comment by edquist** [comment]
> I count 18 FQDNs and it says there are 19 warnings

Yeah the design choice there was how to count warnings.  I decided to make the error/warning count equal to the number of duplicates (as i do in other tests).  So, a single FQDN that appears 10 times counts as 9 warnings.

The set of 18 FQDNs in question here appear 37 times in total, which means 19 of them are duplicate.

**Comment by edquist** [comment]
To point you a bit more directly to the apparent off-by-one discrepancy, in both the list above and in the list in SOFTWARE-3373, all FQDNs in the list appear twice, except for `net2.rc.fas.harvard.edu`, which appears 3 times.  So `net2.rc.fas.harvard.edu` generated 2 warnings since 2 of its 3 appearances were duplicates.

**Comment by edquist** [comment]
Roger - addressed in #156

**Pull request merged**
