### PR TITLE
Update Hewlett Packard Labs LongName

### PR DESCRIPTION
**Pull request by mwestphall**
Per https://github.com/opensciencegrid/topology/pull/3813#pullrequestreview-2009846213, The LongName for this site should be "Hewlett Packard Labs" instead of "Hewlett Packard Laboratory"

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by brianhlin** [comment]
Though do we want to update the site name to reflect the long name?

**Comment by mwestphall** [comment]
> Though do we want to update the site name to reflect the long name?

Which field do we need to update for this? The site folder name, LongName, and Description are all the same.

**Comment by brianhlin** [comment]
Oh sorry, I read the diff backwards. I retract my comment!

**Pull request merged**
