### PR TITLE
Add /osgconnect/protected namespace

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
@djw8605 / @bbockelm , do I have the base path for the issuer correct?  Are the scitoken scopes going to be relative to /osgconnect/protected?

**Comment by djw8605** [comment]
I think no base path. Scopes will have /osgconnect/protected in them. Very similar to the public directory. 

-Derek

**Comment by matyasselmeci** [comment]
OK, done. Can you review?

**Review by djw8605 — APPROVED** [review]
LGTM.  At some point, we should include a "restricted path", but I think this is good.

I don't think this will cause issues because it's the same issuer as another, but we will see.

**Comment by matyasselmeci** [comment]
OK, added a 'restricted path'.

**Pull request merged**
