### PR TITLE
CHTC on OSPool

### PR DESCRIPTION
**Pull request by CannonLock**
Initial PR for registering all the CHTC projects on the OSPool. 

Current errors that @ChristinaLK should speak to:
```
[WARNING] Project is active in OSPool but not found in mapping_all: ece_mawst
[WARNING] Project is active in OSPool but not found in mapping_all: glow
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_statistics_katzfuss
[WARNING] Project is active in OSPool but not found in mapping_all: chtc-visitors
[WARNING] Defaulted to PI Name Anthony Gitter but there were multiple options: ['Anthony Gitter', 'Christopher Magnano']
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_chtcfellowship_2024
[WARNING] Project is active in OSPool but not found in mapping_all: ece_hu
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_waisman_dean
```

These projects that report warnings for being not found in mapping all can be added manually or added to `mapping_all.csv`.

Otherwise a facilitator should run through and add the correct FOSID's to all of these projects.

### CODE REVIEW

**Review by ChristinaLK — APPROVED** [review]
@brianhlin @matyasselmeci I think this is Good Enough ™️ to merge.

**Comment by CannonLock** [comment]
@ChristinaLK 

Want to get these resolved pre or post merge?

```
[WARNING] Project is active in OSPool but not found in mapping_all: ece_mawst
[WARNING] Project is active in OSPool but not found in mapping_all: glow
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_statistics_katzfuss
[WARNING] Project is active in OSPool but not found in mapping_all: chtc-visitors
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_chtcfellowship_2024
[WARNING] Project is active in OSPool but not found in mapping_all: ece_hu
[WARNING] Project is active in OSPool but not found in mapping_all: uwmadison_waisman_dean
```

**Review by matyasselmeci — APPROVED** [review]
LGTM; let me know if you want to make any changes.

**Comment by CannonLock** [comment]
@ChristinaLK confirmed getting this set merged now. 

@matyasselmeci Mind doing the honors?

**Comment by matyasselmeci** [comment]
big inviting green button... clicked!

**Pull request merged**
