### PR TITLE
Create SITE.yaml

### PR DESCRIPTION
**Pull request by biozit**
Adding AggieGrid cluster for State University Of Campinas

### CODE REVIEW

**Comment by biozit** [comment]
Please, should I create the FACILITY.yaml?

**Comment by matyasselmeci** [comment]
Yes, please create a FACILITY.yaml file, using the ID 10183.
Also for the directory name, please use the full name of the university instead of an abbreviation, so "University of Campanas" or "State University of Campanas".

**Comment by biozit** [comment]
I think I create the right file.

**Comment by matyasselmeci** [comment]
I merged your changes in #1605. You should be set now.

**Pull request closed without merging**
