### PR TITLE
Change my.opensciencegrid.org to topology.opensciencegrid.org

### PR DESCRIPTION
**Pull request by jthiltges**

### CODE REVIEW

**Comment by bbockelm** [comment]
Yes!  No more "my.osg.org"!

**Review by brianhlin — APPROVED** [review]
LGTM. FWIW, we should verify that our data consumers (including GRACC @djw8605) are all using `topology.opensciencegrid.org` before removing any DNS entries

**Comment by djw8605** [comment]
GRACC is using my.opensciencegrid.org... who maintains that...

**Comment by matyasselmeci** [comment]
Some WLCG folks are likely to be using my.opensciencegrid.org: https://ggus.eu/?mode=ticket_info&ticket_id=148636

**Pull request merged**
