### PR TITLE
Add squid entries

### PR DESCRIPTION
**Pull request by jxadams**
This edit should add the entry for our squid servers. The FQDN is a round-robin which contains both squids.

### CODE REVIEW

**Comment by jxadams** [comment]
I see the check failed on the first run. I do not have a setting for VOOrganization, which I saw in other configurations. Is this my issue? Or have I failed at some other spot? Possibly a blank line is needed at Line 23?

**Comment by DrDaveD** [comment]
I think you have some indentation problems.  Compare for example the [BNL squid entry](https://github.com/opensciencegrid/topology/blob/7b27d5878a24b9812a2ec73bb97852fa9098eb2e/topology/Brookhaven%20National%20Laboratory/BNL%20ATLAS%20Tier1/BNL-ATLAS.yaml#L271-L291).

Also it says your branch is out of date with master.  In your main branch do "get fetch upstream; get merge upstream/main" and then in your working branch do "git rebase master".   If you haven't yet defined the upstream, do that with "git add remote upstream https://github.com/opensciencegrid/topology.git".  You will need to do git push -f to force push.

**Comment by jxadams** [comment]
I'm doing all my work (so far) in the GitHub web GUI. Do I need to switch to command line work for this? I believe I can do that, but I'll have to puzzle it out first.

**Comment by jxadams** [comment]
I believe I figured out how to to it in the GitHub web GUI...I think.

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
