### PR TITLE
Add two SDSC sites

### PR DESCRIPTION
**Pull request by sfiligoi**
Add "SDSC Flatiron" and "SDSC OSG" sites in the UCSD Facility.

### CODE REVIEW

**Comment by brianhlin** [comment]
Hey Igor, could you give a rundown of why it's necessary to create two new sites?

**Comment by sfiligoi** [comment]
"SDSC Flatiron" will host the StashCache origin for the Flatiron institute.
"SDSC OSG" will host misc services running on the K8 infrastructure.

While both are at SDSC, they are really independent, and operated by a different set of people.

**Comment by sfiligoi** [comment]
Yes.
"SDSC OSG" and "UCSD OSG" are managed by a different set of people.

**Comment by brianhlin** [comment]
How about monitoring/accounting, should they all show up separately in say the [GRACC](https://gracc.opensciencegrid.org/dashboard/db/site-summary?orgId=1)?

**Comment by sfiligoi** [comment]
Yes, all separate

**Pull request merged**
