### PR TITLE
Register the DUNE TIFR CE (FD#72077)

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by brianhlin** [comment]
@jstathas note the new facility "Tata Institute for Fundamental Research" for https://www.tifr.res.in/. Is this ok?

**Review by matyasselmeci — APPROVED** [review]
LGTM

**Comment by brianhlin** [comment]
Oops, I forgot that we were waiting on @jstathas before merging :(. We can always revert this (or change the facility name) if we decide that we need to

**Comment by jstathas** [comment]
Not approved  Please replace for "for" with "of".



Tata Institute of Fundamental Research"
Janet

Janet Stathas
PATh Project Manager
Morgridge Institute for Research

Email: ***@***.******@***.***>
Cell:  608.345.9605

https://morgridge.org<https://morgridge.org/>
https://path-cc.io/


________________________________

**Pull request merged**
