### PR TITLE
Add simple Prometheus update metrics

### PR DESCRIPTION
**Pull request by bbockelm**
We are observing some timeouts in the topology webapp logs around update intervals.  Provide some clarity by adding a Prometheus endpoint and exporting the update timing.

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
LGTM though I don't have any experience with either prometheus-client and or DispatcherMiddleware. How do you test it?

Also, can you add a link to the `/metrics` endpoint to the front page (`src/templates/homepage.html.j2`, under "XML and other machine-readable data")

**Comment by matyasselmeci** [comment]
I can add it too.

**Comment by matyasselmeci** [comment]
I just realized this adds a dependency on prometheus-client to models.py. We can't do that -- models.py is also used by various scripts such as osg-scitokens-mapfile. Sorry, I have to revert.

**Comment by bbockelm** [comment]
@matyasselmeci - how should we resolve this?  Create dummy objects if the import fails?

**Comment by matyasselmeci** [comment]
That's the approach I'm thinking of, too.

**Comment by brianhlin** [comment]
> Create dummy objects if the import fails?

@matyasselmeci did you get around to this?

**Pull request merged**
