### PR TITLE
decommission Cybera-Edmonton

### PR DESCRIPTION
**Pull request by ddavila0**
decommissioning CYBERA-Edmonton due to lack of response

### CODE REVIEW

**Comment by ddavila0** [comment]
@jdost321 do we need to do anything on the factory side?

**Comment by brianhlin** [comment]
This is fine by me but I'd like to get approval from @djw8605 first since they've contributed hours in the past year. If GRACC can handle inactive resources then we can merge.

**Comment by brianhlin** [comment]
Assiging to Derek and Jeff since we're waiting on answers from them before proceeding

**Comment by brianhlin** [comment]
This is safe to merge as is. They last contribute don 2023-07-27 so we can drop them completely over the summer.

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
