### PR TITLE
Update BNL-Belle-II.yaml

### PR DESCRIPTION
**Pull request by xzhao87**
Add WLCGInformation section, setting InteropAccounting: true, so GRACC can monitor the accounting data from these CEs.

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @xzhao87, I think you're going to need to populate the other fields before we can accept this

**Comment by djw8605** [comment]
I think we only need `APELNormalFactor` set.

**Comment by brianhlin** [comment]
@xzhao87 @djw8605 is this something that we still want to get in?

**Comment by xzhao87** [comment]
Sorry, this one fell through the crack. Yes I think we still want to add the norm factor, which I don't have right now unfortunately. The person in charge is on vacation, I will talk to him late this week or early next week to get the norm factor. Thanks. Xin

**Pull request closed without merging**
