### PR TITLE
add WSU SLATE Hosted CE

### PR DESCRIPTION
**Pull request by jdost321**

### CODE REVIEW

**Review by brianhlin — COMMENTED** [review]
@jdost321 I noticed that your corresponding factory commit doesn't appear to include the `GLIDEIN_ResourceName`, was that intentionally left blank?

**Comment by jdost321** [comment]
Yes, I didn't have to override it, it got the right thing from the osg collector:
```<attr name="GLIDEIN_ResourceName" const="True" glidein_publish="True" job_publish="True" parameter="True" publish="True" type="string" value="WSU-GRID"/>```

**Review by brianhlin — APPROVED** [review]
Interesting, thanks!

**Comment by brianhlin** [comment]
@mmascher does the autoconf script set the `GLIDEIN_ResourceName` to the `OSG_Resource` as advertised in the schedd ad from the central collector?

**Pull request merged**
