### PR TITLE
CIT_CMS_T2 One gatekeeper down for upgrade testing to 3.5 and 8.8.4

### PR DESCRIPTION
**Pull request by juztas**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @juztas as noted [here](https://opensciencegrid.org/docs/release/3.5/release-3-5-0/#summary-of-changes), OSG 3.5.0 does not contain HTCondor-CE but I expect that it will make it into 3.5.1.

**Comment by juztas** [comment]
But it will work with newest condor, right? One of the reasons I want to
try out what is missing on our puppet side

**Comment by brianhlin** [comment]
Yup, the OSG 3.4 version of HTCondor-CE should work with HTCondor 8.8.4 from OSG 3.5.0

**Comment by juztas** [comment]
Great. Thanks

**Pull request merged**
