### PR TITLE
Scheduled Quarterly Maintenance

### PR DESCRIPTION
**Pull request by mbatgt**
In preparation for the incoming Maintenance.

### CODE REVIEW

**Comment by edquist** [comment]
Sorry it looks like this still has an error:

```
1 errors encountered:
Georgia Institute of Technology/Georgia Tech/Georgia Tech PACE_downtime.yaml:
  ID: 149485981
  ResourceName: Georgia_Tech_LIGO_Submit_1
  Resource 'Georgia_Tech_LIGO_Submit_1' not found in resource group file
```

**Comment by brianhlin** [comment]
To clarify, it looks like the 3 resources are spread across 2 different files. @mbatgt unless you want to organize your resources like this, we can merge everything together

**Comment by mbatgt** [comment]
Hey Brian,

Merging everything sounds really good to me, unless it’s important to match servers to services on OSG’s end.

Otherwise I can try to create the YAML files but not sure if the result will be any different (I’m not manually adding/changing any thing)

Thank you for your help!
-Memo

---
Mehmet Belgin, Ph.D.
Research Facilitation Lead
Partnership for an Advanced Computing Environment (PACE)
Georgia Institute of Technology
258 4th Street NW, Rich Building, #326
Atlanta, GA  30332-0700
(404) 385-0665

Please cite us if your research benefited from PACE:
http://pace.gatech.edu/how-acknowledgecite-pace

PACE team is growing!
Interested in joining us? Check:
http://pace.gatech.edu/careers



On Feb 12, 2019, at 3:02 PM, Brian Lin <notifications@github.com<mailto:notifications@github.com>> wrote:


To clarify, it looks like the 3 resources are spread across 2 different files. @mbatgt<https://github.com/mbatgt> unless you want to organize your resources like this, we can merge everything together

**Comment by edquist** [comment]
New PR #442

**Pull request closed without merging**
