### PR TITLE
In CHTC.yaml changed submit-4 to submit4

### PR DESCRIPTION
**Pull request by aaronmoate**
To make it consistent with new submit node naming convention

### CODE REVIEW

**Comment by brianhlin** [comment]
@aaronmoate do you need to do the same thing for submit-1 or will that change come later?

**Comment by aaronmoate** [comment]
Later;  submit-1.chtc.wisc.edu's name isn't changing until we
eventually reprovision it, which may be a while.

-Moate

**Comment by brianhlin** [comment]
@djw8605 I forgot to ask during the meeting. Will this change have any effect on records coming from submit 4 over the past year? How do we handle an FQDN and/or resource rename for payload records?

**Comment by aaronmoate** [comment]
FWIW, I changed the resource ID, so I imagine it will be seen as
a completely new resource.

-Moate

**Comment by djw8605** [comment]
In effect, this commit deletes submit-4 and replaces it with submit4.  By convention, we don't delete resources from Topology until a year after the last usage.

Yes, this commit would affect usage in GRACC, as it is deleting a resource.

**Comment by aaronmoate** [comment]
Changes made as requested, I think.

-Moate

**Pull request merged**
