### PR TITLE
Added new project: Fairfield_Kubasik

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks like there's a "Fairfield" organization you can use -- it's used by https://github.com/opensciencegrid/topology/blob/master/projects/cms.org.fairfield.yaml

**Comment by rynge** [comment]
I don't understand the request. Are you saying we do not want "University" in the name?

**Comment by matyasselmeci** [comment]
We want to avoid having duplicates of the same organization with different spellings and I don't think we're able to rename existing projects, at least not if they have records in GRACC.

**Comment by rynge** [comment]
Ok, will remove it then. Hang on

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
