### PR TITLE
Re-register known StashCache servers in topology

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I created a PR against your branch that should hopefully fix the CI issues.

**Comment by zvada** [comment]
> I created a PR against your branch that should hopefully fix the CI issues.

Thanks, @matyasselmeci !

**Comment by matyasselmeci** [comment]
Marian, could you take a look at https://github.com/zvada/topology/pull/1? If you merge that into your branch, the CI failures should go away.

**Comment by matyasselmeci** [comment]
Sorry, didn't notice that the ResourceGroup names must be unique. Can you look at https://github.com/zvada/topology/pull/2?

**Comment by zvada** [comment]
> Sorry, didn't notice that the ResourceGroup names must be unique. Can you look at [zvada#2](https://github.com/zvada/topology/pull/2)?

The change you request I see is a filename with institution name as prefix in the filename. Do we really need this? We have other caches already registered under common file name `topology/<institution>/CachingInfrastructure.yaml`, isn't it good enough to follow that convention? Or do I miss something?

**Comment by matyasselmeci** [comment]
The issue is that the ResourceGroups (i.e. the yaml file names) need to be unique across all of topology.

**Pull request merged**
