### PR TITLE
Hide the controls when taking a picture

### PR DESCRIPTION
**Pull request by djw8605**
Now pictures are like:
OSG Map (6)

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]
LGTM.

**Comment by djw8605** [comment]
Do we need to tag a new release to put in production on tiger?

**Comment by matyasselmeci** [comment]
I think so -- tagging triggers the image build.

**Comment by djw8605** [comment]
Wanna tag 1.3.1?

**Comment by matyasselmeci** [comment]
Done.

**Pull request merged**
