### PR TITLE
disable NERSC-PDSF resources

### PR DESCRIPTION
**Pull request by zvada**
Per discussion with @lagerhardt all resources here retired.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Since you're disabling the resource group, you should just delete the whole file and the corresponding downtime.yaml file.

**Comment by bbockelm** [comment]
Are we sure there are no GRACC records from the past 12 months for PDSF?

**Comment by brianhlin** [comment]
Yup, last records I saw were from January 2017

**Comment by bbockelm** [comment]
Sounds good.  In the future, we should record the fact we performed the check when we delete -- just in case we ever need to revisit our old decisions!

**Comment by brianhlin** [comment]
@zvada please remove the resource group and corresponding downtime file instead

**Comment by zvada** [comment]
> @zvada please remove the resource group and corresponding downtime file instead

sorry, slipped off of attention. @brianhlin should we add into an appropriate place in docs how to retire resource clean way? Also, what quick URL it is to check for the last records. Or, at a minimum, reflect the process in a note in the [development section](https://github.com/opensciencegrid/topology/tree/master/src) which explains `active|disable` or something...

**Comment by matyasselmeci** [comment]
I fixed the merge conflicts and merged the changes in #632.

**Pull request closed without merging**
