### PR TITLE
Add convert() function so resourcegroup_yaml_to_xml.py can be used as a module

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Crap, don't merge this yet -- I broke something.

**Comment by matyasselmeci** [comment]
OK, fixed.

**Comment by djw8605** [comment]
Could you edit the `app.py` in the root directory to call the convert function?

**Comment by matyasselmeci** [comment]
Done. Takes about 10 seconds to render on my laptop.

**Pull request merged**
