### PR TITLE
Added registration of four CVMFS Squids

### PR DESCRIPTION
**Pull request by cvuosalo**

### CODE REVIEW

**Comment by brianhlin** [comment]
@cvuosalo do these squid servers serve the same resource? Do you have a DNS round robin entry set up for these three squids perchance?

**Comment by cvuosalo** [comment]
@brianhlin: cvmfscache01 and 02 serve our data and worker nodes, while cvmfscache03 and 04 serve our interactive nodes. They are not set up as round-robin.

**Comment by brianhlin** [comment]
@cvuosalo: would you be able to get two DNS round-robin entries, one for cvmfscache{01,02} and one for cvmfscache{03,04}? I believe that's what the WLCG prefers for registration.

**Comment by cvuosalo** [comment]
@brianhlin: I don't understand. You want round-robin entries for Squids that are not round robin???
Could you please specify the exact syntax that is required?

**Comment by brianhlin** [comment]
@cvuosalo perhaps I'm misreading your initial comment. cvmfscache01 and 02 server your data and worker nodes but they're not round-robined? Similarly for cvmfscache03 and 04 for the interactive nodes?

**Comment by cvuosalo** [comment]
@brianhlin: Yes, that is correct. No round robins involved.

**Pull request merged**
