### PR TITLE
adding CMS UAF Project

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Comment by ddavila0** [comment]
@rynge could you please help me with the review/merge of this PR, please?

**Comment by rynge** [comment]
CMS might have some input if they want to make it work in their reporting infrastructure. For the open pool, we usually use [Institution]_[PI] as project name.

**Comment by brianhlin** [comment]
Also roping in @matyasselmeci in case there are Topology-specifics.

@lmichael107 not sure if you want other VOs to follow your project naming conventions or if that's something that's limited to the OSG VO

**Comment by fkw888** [comment]
I'm proposing that we account via GRACC the submit hosts we operate with CMS credentials for the UCSD T2 center.
We should have done this years ago. 
My group operates these submit hosts. We do so for people with login credentials at UCSD. Basically, collaborators of ours.

I'm ok to follow any convention you want. But please, let's not delay this by a year by involving CMS.
(just look at the nightmare with the HPC naming convention)
If you want the project name to be UCSD_Wuerthwein_CMSUAF then I'm ok with that.

thanks, frank

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
No objections from a topology POV.

**Pull request merged**
