### PR TITLE
Add StashCache Origin to UW-Madison/WIPAC/IceCube

### PR DESCRIPTION
**Pull request by vbrik**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks good, though you'll also need to modify `/virtual-organizations/IceCube.yaml` to add your new origin to the `AllowedOrigins` list. Let me know if you need help with that.

**Comment by vbrik** [comment]
> Looks good, though you'll also need to modify `/virtual-organizations/IceCube.yaml` to add your new origin to the `AllowedOrigins` list. Let me know if you need help with that.

Done. Could this commit be merged now?

**Comment by matyasselmeci** [comment]
Hi Vlad, what's the FQDN of this server going to be?

**Comment by vbrik** [comment]
stash-origin.icecube.wisc.edu

**Comment by matyasselmeci** [comment]
also, I put you and Steve Barnet down as the contacts for that host. Is that OK?

**Comment by vbrik** [comment]
Yes, that is good

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
