### PR TITLE
Standardize WSU information

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by brianhlin** [comment]
Since this has an FQDN and site name change, I checked to make sure that there weren't any GRACC records for this CE in the past year and we're in the clear. Is their cluster really named GRID_ce2? Otherwise this looks fine to me.

**Comment by mmascher** [comment]
Hi @brianhlin , I think the cluster is really named GRID, I added ce2 to mantain backward compatibility (I do not have to change the factory entry name for example)

**Comment by mmascher** [comment]
@brianhlin About the old gracc records, I believe this was reporting, for example:

```[root@pearc-ce-2 ~]# grep "new records sent successfully: [^0]" /var/log/gratia/2019-12-06.log 
10:29:48 CST Gratia: End of execution summary: new records sent successfully: 6
10:38:27 CST Gratia: End of execution summary: new records sent successfully: 6
11:03:51 CST Gratia: End of execution summary: new records sent successfully: 2
11:46:51 CST Gratia: End of execution summary: new records sent successfully: 5
12:08:06 CST Gratia: End of execution summary: new records sent successfully: 5
15:37:02 CST Gratia: End of execution summary: new records sent successfully: 5
15:51:01 CST Gratia: End of execution summary: new records sent successfully: 5
16:03:36 CST Gratia: End of execution summary: new records sent successfully: 4
16:35:51 CST Gratia: End of execution summary: new records sent successfully: 4
16:54:51 CST Gratia: End of execution summary: new records sent successfully: 13
17:23:54 CST Gratia: End of execution summary: new records sent successfully: 1
19:29:47 CST Gratia: End of execution summary: new records sent successfully: 2
19:51:11 CST Gratia: End of execution summary: new records sent successfully: 1
21:12:15 CST Gratia: End of execution summary: new records sent successfully: 2
22:12:36 CST Gratia: End of execution summary: new records sent successfully: 1
22:50:07 CST Gratia: End of execution summary: new records sent successfully: 1
23:57:07 CST Gratia: End of execution summary: new records sent successfully: 2
```

I do not know if we were hit by the same issue that happened at Bridges (maybe @djw8605 knows)

It would be nice to recover old data and show it on gracc if possible, this is a CC* CE

**Comment by djw8605** [comment]
the records are being quarantined.  Is it running an older version of Condor?  GRACC is complaining "MissingStartTime"...  There was a bug a while ago in HTCondor that grid jobs were not getting start time inserted, I think.

**Comment by mmascher** [comment]
yes @djw8605 it was an old version of condor. I completely reinstalled the CE on a new machine.

**Comment by mmascher** [comment]
@brianhlin I'll change the PR so that the old resource gets retired.

**Comment by mmascher** [comment]
Actually, I think it is cleaner if I close this one. Opened: https://github.com/opensciencegrid/topology/pull/936

**Pull request closed without merging**
