### PR TITLE
Adding NCAR S3 origin

### PR DESCRIPTION
**Pull request by biozit**
Adding NCAR S3 origin

### CODE REVIEW

**Review by brianhlin — CHANGES_REQUESTED** [review]
It looks like your indentation is off: could you indent all the lines you added by 2 spaces?

**Comment by biozit** [comment]
fixed

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
@brianhlin need anything else for this or can I merge?

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
