### PR TITLE
make Doug Benjamin the new primary contact for BNL-SDCC

### PR DESCRIPTION
**Pull request by edquist**
https://support.opensciencegrid.org/a/tickets/67235

### CODE REVIEW

**Comment by brianhlin** [comment]
I believe @xzhao87 should still be a contact on these resources. Could you add him as secondary?

**Comment by edquist** [comment]
Sure thing.  I guess it was ambiguous in the FD ticket but it had sounded to me like Doug was replacing Xin.

**Comment by edquist** [comment]
Doug confirms Xin will stay on as the secondary contact

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
