### PR TITLE
Support public read / auth write

### PR DESCRIPTION
**Pull request by matyasselmeci**
SOFTWARE-5727; even if a namespace has PUBLIC auth, if it also has SciTokens auth information, generate a scitokens.conf for the origin but make sure "usetokenonread" isn't set in the namespaces json.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
This is currently deployed on topology-itb.

**Comment by matyasselmeci** [comment]
@brianhlin , @djw8605 , can you review this or suggest other reviewers?

**Comment by brianhlin** [comment]
@mwestphall can you take a look at this sometime over the next week or so?

**Comment by matyasselmeci** [comment]
I'd like to have this in before I start work on https://opensciencegrid.atlassian.net/browse/SOFTWARE-5760 since they affect the same code.

**Comment by biozit** [comment]
Do you think I can help somehow?

**Review by mwestphall — APPROVED** [review]
LGTM

**Comment by biozit** [comment]
Can I start to test it?

**Comment by biozit** [comment]
Looks ok, still testing.

**Pull request merged**
