### PR TITLE
New project: UTSA_Anantua

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by jstathas** [comment]
No - the value should be "The University of Texas at San Antonio<https://carnegieclassifications.acenet.edu/institution/the-university-of-texas-at-san-antonio/>"

(I am aware that this is inconsistent with the other University of Texas institution values we have - which we will be standardizing to the correct name at some point.)







Janet Stathas (she/her)

Project Manager

Morgridge Institute for Research

PATh<https://path-cc.io/>

Email: ***@***.***

Mobile: 608.345.9605

________________________________

**Comment by rynge** [comment]
I can update the PR for that, but one concern I have is that the extra "The" could be confusing in lists and reports, where the entry will be sorted in an unexpected way.

**Comment by jstathas** [comment]
Mats,

True, but the decision was discussed with Brian B. There is a plan getting developed to clean up institution names to the standard.

(Department of Education and Carnegie-Mellon institution names).

https://ope.ed.gov/dapip/#/home

Janet



Janet Stathas (she/her)

Project Manager

Morgridge Institute for Research

PATh<https://path-cc.io/>

Email: ***@***.***

Mobile: 608.345.9605

________________________________

**Comment by rynge** [comment]
Ok, I have updated the name

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
