### PR TITLE
adding /knightlab namespace

### PR DESCRIPTION
**Pull request by biozit**
adding /knightlab namespace

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I'm not sure having an authenticated namespace _under_ a public namespace works. I think the public cache instances are going to serve that data without authentication.

**Comment by biozit** [comment]
@matyasselmeci The idea is to send and read data publicly using HTTP requests.

**Comment by matyasselmeci** [comment]
Yes, but /knightlab/mirror/ncbi-genbank-refseq will also be public. Is that what you want?

**Comment by biozit** [comment]
yes, it is

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
ok :)

**Pull request merged**
