### PR TITLE
Datacenter power upgrades (part 2)

### PR DESCRIPTION
**Pull request by hseverini**

### CODE REVIEW

**Comment by bbockelm** [comment]
@matyasselmeci -- is it clear to you what the CI failure is?  The traceback for the HTTP 500 doesn't look obvious.

**Comment by hseverini** [comment]
Hi all,

could it be that the parentheses in the reason -- (part 2) -- is causing
problems, maybe because they're not properly escaped? Just an idea,
I don't know anything about this system. :)

Thanks,

	Horst

**Comment by mwestphall** [comment]
The CI pipeline failure appears to be due to an issue with an external service (which we really should investigate) and not anything specific to this PR, I'll merge it in bypassing the CI checks as a workaround.

**Review by mwestphall — APPROVED** [review]

**Comment by hseverini** [comment]
Thanks all!

	Horst

**Pull request merged**
