### PR TITLE
Create aionedge.yaml

### PR DESCRIPTION
**Pull request by shreyb**
This is a request to add an aionedge project to OSG topology so that a CVMFS repository can be created for aionedge.  This will be used by DUNE and SBND, Fermilab experiments.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
As far as I'm aware, projects are not used to create areas for CVMFS; that information is in the "virtual-organizations" directory.

**Comment by matyasselmeci** [comment]
Yes, that should work. @ppaschos, have you been working with them? Do this sound good to you?

**Comment by ppaschos** [comment]
These are in Ken Herner and Steven Timm's court

**Comment by ppaschos** [comment]
If this is a repository to will be used by mainly fermilab experiments, can't it not be under the fermilab VO?

**Comment by ppaschos** [comment]
yes that's exactly what I meant. FNAL being the parent  VO means that you don't have to assign/create a separate one.. in my opinion unless there are other 'political' issues here.

**Comment by shreyb** [comment]
Let me just ask Ken to make sure, but I think that'll be OK.  Thanks very much @ppaschos  and @matyasselmeci  for walking me through this.

@kherner:  are you OK with us modeling the `aionedge` entry after the `LArSoft` entry here?  Since AIOnEdge isn't actually a VO, per se, we'd have Fermilab be the parent VO, like it is in the LArSoft entry (https://github.com/opensciencegrid/topology/blob/master/virtual-organizations/LArSoft.yaml).  I think as long as this still allows AIOnEdge to have the repo name `aionedge.opensciencegrid.org`, the requestors/stakeholders don't really care how we have the OSG end set up.

**Comment by kherner** [comment]
Yes, let's just put it under the Fermilab VO. After all several of the FIFE experiments already are.

**Comment by shreyb** [comment]
Great - then I'm good to close this PR out and open another one under `virtual-organizations`.

**Comment by matyasselmeci** [comment]
I merged #3211; we no longer need this PR open.

**Pull request closed without merging**
