### PR TITLE
NERSC-Perlmutter resource group (FD #68597)

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Steve says it's intentional for both to have the same FQDN.

**Comment by bbockelm** [comment]
NACK.  Resources should have a unique FQDN.  Existing duplicates are mistakes we should have eliminated by now and I don't want to dig the hole deeper.

**Comment by retzkek** [comment]
Proposed FQDNs:

```
NERSC-Perlmutter-CPU: perlmutter-cpu.hepcloud.fnal.gov
NERSC-Perlmutter-GPU: perlmutter-gpu.hepcloud.fnal.gov 
```

**Comment by matyasselmeci** [comment]
Thanks Kevin, I used those new FQDNs, listed the real ones in FQDNAliases and added a comment to explain. @bbockelm does it look better now?

**Review by brianhlin — APPROVED** [review]
LGTM, though I'm not 100% clear how the accounting works such that the separate resources are required

**Pull request merged**
