### PR TITLE
creating /nrp/sdsc

### PR DESCRIPTION
**Pull request by biozit**
@djw8605

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @biozit what's this for? Is there a ticket that we can reference?

**Comment by djw8605** [comment]
/nrp/sdsc was an existing namespace used by the NRP.  We are restarting use of it.

**Comment by bbockelm** [comment]
Are we sure `/nrp` is really what we want?

Origins can support any number of namespace prefixes.  My understanding was this was being revived for XenonNT so perhaps `/xenon/sdsc` is more appropriate?

**Comment by djw8605** [comment]
Maybe this is conflating 2 different things.  This requesting is reviving it for the FPGA software for the PNRP.

**Comment by bbockelm** [comment]
> Maybe this is conflating 2 different things

Possibly!  That's why I was asking :)

So, if this is really for NRP itself, PR makes sense.

**Review by brianhlin — APPROVED** [review]
Got it, LGTM

**Pull request merged**
