### PR TITLE
ResourceAllocation support (ITB)

### PR DESCRIPTION
**Pull request by matyasselmeci**
SOFTWARE-4563

### CODE REVIEW

**Comment by matyasselmeci** [comment]
(disabled edits; any suggestions from here should go into the non-itb pr/SOFTWARE-4563.resourceallocation branch)

**Comment by edquist** [comment]
Now that you have gotten your branch to the point that you are requesting a review, would you be terribly opposed to rebasing your branch against `itb`?  If you want you can reset `itb` to `master` and force push that first.

There's just a lot going on in the commit list for this PR that i have a feeling are not related to your changes...

**Comment by matyasselmeci** [comment]
Weird, I merged itb before making the PR. I'll try a rebase, let's see what happens...

**Comment by matyasselmeci** [comment]
Argh! I made the PR against the wrong branch.

**Pull request closed without merging**
