### PR TITLE
Set old SL6 CE as Disabled.  Update total storage in the SE

### PR DESCRIPTION
**Pull request by a2bobball**
Disable AGLT2_SL6, and update our total storage size.

### CODE REVIEW

**Comment by brianhlin** [comment]
@a2bobball Could you revert the change to the `Disable` field? It's the same as deleting a resource and we can't remove resources that have GRACC records in the past year.

To indicate that a resource is retired, we set `Active: false`, which I've done for AGLT2_SL6 already.

**Comment by a2bobball** [comment]
Note that the Active switch is not documented in the template-resourcegroup.yaml file.

**Comment by brianhlin** [comment]
There are some other resources with `Active: false` at other sites. We'll fixup the template file, thanks for the heads up!

**Comment by brianhlin** [comment]
Also, we hope to address this hole in our documentation tomorrow. You can track progress via this [JIRA ticket](https://opensciencegrid.atlassian.net/browse/SOFTWARE-3371) or expect to see detailed documentation by sometime next week [here](https://opensciencegrid.org/docs/common/registration/)

**Pull request merged**
