### PR TITLE
Add OSDF origin server to SDSC-NSG

### PR DESCRIPTION
**Pull request by mkandes**
NSG would like to evaluate the capabilities provided by running its own origin server within the OSDF.

### CODE REVIEW

**Comment by mkandes** [comment]
Are there IP addresses and/or IP spaces that we can use to restrict the inbound traffic to the origin from the OSDF caches?

**Comment by biozit** [comment]
Do you mean let only the caches access the origin or some caches access the origin?

**Comment by mkandes** [comment]
Fabio,

The IT team who helps manage the VM we're testing on the origin service on manages its firewall. If we can whitelist the caches and/or other systems that need the inbound access on the required ports, that would be helpful security-wise for them. Does that make sense?

Marty
________________________________

**Comment by biozit** [comment]
Sure, those are the caches, port TCP: 1094 8443 


daejeon-kreonet-net.nationalresearchplatform.org
ds-102-11-18.cr.cnaf.infn.it
dtn-pas.bois.nrp.internet2.edu
dtn-pas.cinc.nrp.internet2.edu
dtn-pas.jack.nrp.internet2.edu
fiona-r-uva.vlan7.uvalight.net
its-condor-xrootd1.syr.edu
ligo.hpc.swin.edu.au
mghpcc-cache.nationalresearchplatform.org
osg-chicago-stashcache.nrp.internet2.edu
osg-gftp2.pace.gatech.edu
osg-houston-stashcache.nrp.internet2.edu
osg-kansas-city-stashcache.nrp.internet2.edu
osg-new-york-stashcache.nrp.internet2.edu
osg-sunnyvale-stashcache.t2.ucsd.edu
sc-cache.chtc.wisc.edu
sdsc-cache.nationalresearchplatform.org
stash-cache.osg.chtc.io
stash.farm.particle.cz
stashcache.edi.scotgrid.ac.uk
stashcache.jinr.ru
stashcache.t2.ucsd.edu
unl-cache.nationalresearchplatform.org
xcachevirgo.pic.es

redirector
redirector.osgstorage.org port: TCP 1094

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
@mkandes before you get much further with this process, I think Frank would like to have a meeting to discuss your plans. I'll sort out details there and reach out to you off-PR.

**Pull request merged**
