### PR TITLE
Replace CHTC origin server with sc-origin2000.chtc.wisc.edu

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by djw8605** [comment]
If it's a CNAME to the other name, why make any changes at all?

**Comment by matyasselmeci** [comment]
sc-origin2000 is the real name, sc-origin will be the CNAME once we switch over. I suppose I could [manually set the FQDN](https://opensciencegrid.org/docs/data/stashcache/install-origin/#manually-setting-the-fqdn-optional) instead, though the DN is still going to change. Would that be better?

**Comment by djw8605** [comment]
The DN doesn't have to change if it's a CNAME, right?  Or it can be a SAN?

**Comment by matyasselmeci** [comment]
We're also switching CAs from InCommon to Let's Encrypt.

**Pull request merged**
