### PR TITLE
Add downtime for INFN_CNAF_OSDF_CACHE due to overloaded

### PR DESCRIPTION
**Pull request by biozit**
Add downtime for INFN_CNAF_OSDF_CACHE due to overload. The node is HDD based, we are testing if the node should be "only CVMFS" or "only OSDF".

### CODE REVIEW

**Comment by brianhlin** [comment]
@biozit as discussed on Slack, please flesh out the description here since you are not the admin of the site

**Comment by biozit** [comment]
done

**Comment by brianhlin** [comment]
@biozit I don't see any additional changes in the PR. Where'd you add them?

**Comment by biozit** [comment]
I added in the PR description

**Comment by brianhlin** [comment]
Please also change the `Description` field in the downtime itself

**Comment by biozit** [comment]
done

**Pull request merged**
