### PR TITLE
Update UColorado_HEP.yaml

### PR DESCRIPTION
**Pull request by doug1977**
Attempting to register multiple squid servers

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi Doug, do these squids serve all the same worker nodes? Because we suggest having a single DNS round-robin entry in that case (https://opensciencegrid.org/docs/data/frontier-squid/#registering-frontier-squid). If not, I'll add a few suggestions that you'll need to accept so that we can merge this in.

Also, do you have a backup contact for the resources?

**Comment by matyasselmeci** [comment]
Hi Doug,
We just need to know if there's a round-robin DNS entry for these squids. If there isn't, we register the individual squids; if there is, we register that DNS entry instead.
Either way, I can take care of the syntax.

**Comment by doug1977** [comment]
Greetings,
No there is not a DNS round robin.
Thank you,
doug

**Comment by matyasselmeci** [comment]
Ah, Brian just told me that you weren't doing round-robin.

**Pull request merged**
