### PR TITLE
Replace CHTC contact IDs with CILogonIDs

### PR DESCRIPTION
**Pull request by edquist**
If the case-insensitive changes from #2495 / v1.18.2 work then the checks should pass this time...

### CODE REVIEW

**Comment by edquist** [comment]
Good, checks are passing again now, so the Carl Edquist / CARL EDQUIST difference is accepted by the tests.

**Comment by edquist** [comment]
Per Brian B i'm doing this for CHTC contacts also.  Because we don't have a CHTC Staff flag in the contact db, i am limiting this to the contacts that are registered with resources in the CHTC site.

**Comment by edquist** [comment]
@matyasselmeci @brianhlin ping a ling ding when you getta chance

**Review by matyasselmeci — APPROVED** [review]
Well sed!

**Comment by edquist** [comment]
>Well sed!

"sed, sed, have sed", or is simple past "sedded" ?

**Pull request merged**
