### PR TITLE
update caching services

### PR DESCRIPTION
**Pull request by ivukotic**
now it corresponds to what is actually deployed.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks like there's a duplicate AGLT2-squid-5 in the new file. Can you take a look?

**Comment by ivukotic** [comment]
Hi,

My mistake. Can you please change it to -6 or something?
Also I did not add ID. Not sure how to select a number.

Best,
               Ilija

**Comment by brianhlin** [comment]
@djordan66 @jlstephen @LincolnBryant FYI

**Comment by ivukotic** [comment]
Hi,

This is AGLT2 change.
I agreed on it with Wenjing and Shawn.
Ilija


Best,
   Ilija Vukotic
________________________________

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
