### PR TITLE
Add WISC-PATH site and OSPool backfill containers

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
That one's already registered at `CHTC/PATh_facility.yaml`

**Comment by brianhlin** [comment]
Ah ok, I was looking for `WISC-PATH-EP`, which is what we've reported to the GRACC. I say we get rid of the CHTC resource group in favor of this one to match the other PATH sites under UW unless @bbockelm wants these hours to be credited to CHTC

**Comment by matyasselmeci** [comment]
I'm fine either way. What do you say, @bbockelm?

**Comment by matyasselmeci** [comment]
@bbockelm what's your opinion on having the CHTC Site with a PATh_facility ResourceGroup (as we do currently) versus having a WISC-PATH Site with a WISC-PATH ResourceGroup?

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
Merging this since, as you said, this name has already reported hours. I'll get rid of the other one in a different PR.

**Pull request merged**
