### PR TITLE
Map Fix

### PR DESCRIPTION
**Pull request by CannonLock**
Use getter for resources instead of static assignment at construction

### CODE REVIEW

**Comment by CannonLock** [comment]
Origins: 10
Caches: 17
Origin and Caches: 5

`{'AmsterdamPRP': {'is_cache': True, 'is_origin': False}, 'CHTC': {'is_cache': True, 'is_origin': True}, 'Caltech LIGO': {'is_cache': False, 'is_origin': True}, 'Cardiff Computing Cluster': {'is_cache': True, 'is_origin': False}, 'SDSC OSG': {'is_cache': False, 'is_origin': True}, 'FZU': {'is_cache': True, 'is_origin': False}, 'Georgia Tech': {'is_cache': True, 'is_origin': False}, 'Nebraska-Lincoln': {'is_cache': True, 'is_origin': True}, 'Internet2Chicago': {'is_cache': True, 'is_origin': False}, 'Internet2GreatPlains': {'is_cache': True, 'is_origin': False}, 'Internet2Houston': {'is_cache': True, 'is_origin': False}, 'Internet2Manhattan': {'is_cache': True, 'is_origin': False}, 'Internet2Sunnyvale': {'is_cache': True, 'is_origin': False}, 'Institute for Astronomy HURP': {'is_cache': False, 'is_origin': True}, 'INFN-T1': {'is_cache': True, 'is_origin': False}, 'Information Technology Center': {'is_cache': False, 'is_origin': True}, 'WIPAC': {'is_cache': False, 'is_origin': True}, 'JINR_Cloud': {'is_cache': True, 'is_origin': False}, 'JLAB': {'is_cache': False, 'is_origin': True}, 'T3_KR_KISTI': {'is_cache': True, 'is_origin': False}, 'NRP': {'is_cache': True, 'is_origin': True}, 'PIC': {'is_cache': True, 'is_origin': False}, 'San Diego Supercomputer Center': {'is_cache': True, 'is_origin': True}, 'SU ITS': {'is_cache': True, 'is_origin': False}, 'SUT - OzStar': {'is_cache': True, 'is_origin': False}, 'UCSD OSG': {'is_cache': True, 'is_origin': False}, 'UCL-INGRID': {'is_cache': False, 'is_origin': True}, 'UChicago': {'is_cache': True, 'is_origin': True}, 'UConn-HPC': {'is_cache': False, 'is_origin': True}, 'UConn-OSG': {'is_cache': False, 'is_origin': True}, 'Scotgrid ECDF': {'is_cache': True, 'is_origin': False}, 'Utah-SCI-VDC': {'is_cache': False, 'is_origin': True}}`

**Comment by CannonLock** [comment]
OSG_Map-10

Screen Shot 2023-01-11 at 11 17 36 AM

**Comment by CannonLock** [comment]
Images show the new card with a resource group now missing due to not being production 

https://github.com/opensciencegrid/topology/tree/master/topology/University%20of%20California%20San%20Diego/SDSC%20OSG

**Comment by biozit** [comment]
> OSG_Map-10
> 
> Screen Shot 2023-01-11 at 11 17 36 AM

it is amazing!

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
The topology tests validate the schema so it looks like the schema change doesn't cause any problems.

**Pull request merged**
