### PR TITLE
verify contacts (SOFTWARE-3329)

### PR DESCRIPTION
**Pull request by edquist**
various checks for contacts and consistency with the contact repo

### CODE REVIEW

**Comment by edquist** [comment]
This is still WIP - i'm creating the PR for now to get the CI error output

**Comment by edquist** [comment]
Current set of contact errors (only includes resource contact checks) -

it's almost all for missing `ContactLists` sections; the other two items are a name mismatch (`Jadir Silva` vs `Jadir Marra da Silva`) and a contact missing from the contact repo (`Nathan Yehle (disabled)`).

```
*** Resources must contain a ContactLists section
In 'CENF_NeutrinoPlatform/CENF/CENF_Neutrino_Computing_Cluster.yaml', Resource 'CENF_NeutrinoCluster' has no ContactLists
In 'Fermi National Accelerator Laboratory/FermiGrid/FNAL_FIFE_SUBMIT.yaml', Resource 'FIFEBATCH2' has no ContactLists
In 'High Performance Computing Facility - University of Puerto Rico/High Performance Computing Facility - University of Puerto Rico/UPR_HPCF.yaml', Resource 'Nanobio_CE' has no ContactLists
In 'Indiana University/ILS/Jupiter.yaml', Resource 'ILS_compute' has no ContactLists
In 'Indiana University/ILS/cns.yaml', Resource 'cns1' has no ContactLists
In 'Indiana University/ILS/cns.yaml', Resource 'cns2' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'FZU_NOVA' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'FZU_NOVA_CE' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'FZU_OSG_CE1' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'FZU_OSG_CE2' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'perfSONAR_FZU_bandwidth' has no ContactLists
In 'Institute of Physics ASCR/FZU/FZU.yaml', Resource 'perfSONAR_FZU_latency' has no ContactLists
In 'Institute of Plasma Physics, Chinese Academy of Sciences/shenma high performance computing at IPP CAS/TRANSP_simulations_for_EAST.yaml', Resource 'shenma_duhongfei' has no ContactLists
In 'Kansas State University/Beocat/Beocat.yaml', Resource 'Beocat_KSU_CE' has no ContactLists
In 'Kennesaw State University/Kennesaw State University/Kennesaw_Dell_Nodes.yaml', Resource 'Kennesaw_Dell_Nodes' has no ContactLists
In 'Northwestern University/NU Tier3/NU_CMS_TIER3_CE.yaml', Resource 'NU_CMS_TIER3_CE' has no ContactLists
In 'Northwestern University/NU Tier3/NU_CMS_TIER3_SE.yaml', Resource 'NU_CMS_TIER3_SE' has no ContactLists
In 'UC Irvine/UCIT3/University of California Irvine.yaml', Resource 'UCI_ATLAS_GRIDFTP' has no ContactLists
*** Contact names must match in contact repo
In 'Universidade Estadual Paulista/SPRACE/SPRACE.yaml', Resource 'BR-Sprace BW' Secondary Administrative Contact '2f652c47255fc4d6b45f19667be57b8517ea006f' (Jadir Silva) does not match name in contact repo (Jadir Marra da Silva)
In 'Universidade Estadual Paulista/SPRACE/SPRACE.yaml', Resource 'BR-Sprace BW' Primary Resource Report Contact '2f652c47255fc4d6b45f19667be57b8517ea006f' (Jadir Silva) does not match name in contact repo (Jadir Marra da Silva)
In 'Universidade Estadual Paulista/SPRACE/SPRACE.yaml', Resource 'T2_BR_SPRACE-squid1' Primary Miscellaneous Contact '2f652c47255fc4d6b45f19667be57b8517ea006f' (Jadir Silva) does not match name in contact repo (Jadir Marra da Silva)
In 'Universidade Estadual Paulista/SPRACE/SPRACE.yaml', Resource 'T2_BR_SPRACE-squid2' Primary Miscellaneous Contact '2f652c47255fc4d6b45f19667be57b8517ea006f' (Jadir Silva) does not match name in contact repo (Jadir Marra da Silva)
*** Contact IDs must exist in contact repo
In 'University of Chicago/MWT2 ATLAS UC/MWT2.yaml', Resource 'MWT2_CE_UC' has unknown Primary Submitter Contact '6d5915fca586e4702c3f4ecbf56750132c6896c2' (Nathan Yehle (disabled))
In 'University of Maryland/UMD-IGS/UMD-IGS.yaml', Resource 'UMD-IGS-CE' has no ContactLists
In 'University of Pittsburgh/UPittTier3/UPittTier3.yaml', Resource 'UPittTier3_DTN' has no ContactLists
In 'University of Wisconsin Milwaukee/UW Milwaukee Physics/LIGO_UWM_NEMO.yaml', Resource 'LIGO_UWM_NEMO' has no ContactLists
In 'University of Wisconsin/Discovery/Discovery.yaml', Resource 'Discovery_PerfSonar_Bandwidth' has no ContactLists
In 'University of Wisconsin/Discovery/Discovery.yaml', Resource 'Discovery_PerfSonar_Latency' has no ContactLists
```

**Comment by matyasselmeci** [comment]
Are the `***` lines supposed to be section dividers or something? Because it looks like the errors are mixed between sections, e.g. `In 'University of Maryland/UMD-IGS/UMD-IGS.yaml', Resource 'UMD-IGS-CE' has no ContactLists` is under `Contact IDs must exist in contact repo`.

Otherwise it looks good. I think we should fix or drop the invalid contacts before merging this. Also, @brianhlin, should missing ContactLists be a warning or an error?

**Comment by brianhlin** [comment]
It will have to be a warning until we deal with the resources without ContactLists

**Comment by edquist** [comment]
This branch is WIP so please don't judge to harshly yet :)

> Are the `***` lines supposed to be section dividers or something?
Not exactly, they're just there to notify the reader of the rule that is being violated - they get printed once for the first time that each type of error appears.  They are not grouped in the output because a single pass is done of all the resources, rather than one pass per type of error/check.

I think i agree though that it'd be prettier to display the errors grouped by type, so before this is done i might try to do that.

**Comment by matyasselmeci** [comment]
> It will have to be a warning until we deal with the resources without ContactLists

Hey guess what! We just dealt with resources without ContactLists!

Maybe it's time to revisit this PR...

**Comment by brianhlin** [comment]
I've got some a commit on top of this to also detect missing admin or sec contacts + separate the error messages into types. I'll submit a PR once I resolve the merge conflicts from the flurry of work this afternoon.

**Comment by edquist** [comment]
So, I've backed this PR up to before adding the Admin/Security contact checks, since this PR otherwise actually succeeds now, since we (@matyasselmeci) have cleaned up the ContactLists.

I've moved the Admin/Security contact checks to a separate branch:

https://github.com/edquist/topology/tree/SOFTWARE-3329.verify-contacts2/

which I'll start a new PR for once we merge this one.

**Comment by edquist** [comment]
Note the above commits separate out the different tests so that the output is per-error type.

I've added the admin/security contact checks, which are generating the current CI errors for 
d77ac81.

I'm going to downgrade these errors to warnings so that CI passes again and we can finally merge this...

**Comment by edquist** [comment]
CI passes for 3626c44 now with warnings.  @matyasselmeci, can you review/merge?

**Pull request merged**
