### PR TITLE
Change to BNL Squid URL

### PR DESCRIPTION
**Pull request by deesto**
Changed DNS alias from old 'racf' record to 'sdcc'.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Hi John,
Two things:
1. Could you put the Administrative Contact change in a separate commit than the URL change? We'd like the commit message to match what the commit actually contains...
2. We have you down as "John S. De Stefano Jr." in our contacts DB, not "John Steven De Stefano Jr". Could you fix that in your pull request?
Thanks,
-Mat

**Comment by matyasselmeci** [comment]
I made a fixed version in #320; let me know if you're OK with it.

**Comment by matyasselmeci** [comment]
Fixed in #320

**Comment by brianhlin** [comment]
@matyasselmeci  you can close issues directly from PRs https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

**Pull request closed without merging**
