### PR TITLE
Add colors to map points for different type of sites

### PR DESCRIPTION
**Pull request by djw8605**
~~Do not merge yet~~ Merge away!

### CODE REVIEW

**Comment by djw8605** [comment]
image (5)

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
@djw8605 this still good to merge?

**Comment by djw8605** [comment]
Nope, it was requested to have a "default" view with the old green dots.  So I'm adding that, then we should be good to merge.

**Comment by djw8605** [comment]
Ok, this is ready to be merged.

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
