### PR TITLE
Add Université catholique de Louvain (uclouvain.be)

### PR DESCRIPTION
**Pull request by matyasselmeci**
https://support.opensciencegrid.org/a/tickets/66170

### CODE REVIEW

**Comment by matyasselmeci** [comment]
So far this PR only contains the facility; we're probably going to add a site and some resources before merging.

**Comment by matyasselmeci** [comment]
Andres is waiting for this to get merged before he can register the site and resources.

**Review by brianhlin — APPROVED** [review]
LGTM, sorry for the hold-up

**Comment by matyasselmeci** [comment]
np, 10 minutes is not a holdup

**Pull request merged**
