### PR TITLE
verify projects

### PR DESCRIPTION
**Pull request by edquist**
in particular, the project Name has to match the filename.

this is dumb/redundant, but maybe we oughta have a check for it until
we remove the Name field.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
I dunno. Changing `src/webapp/project_reader.py` to take the `Name` field from the filename instead of the contents is trivial, and then we can get rid of the `Name` field from the project yaml files.

**Comment by edquist** [comment]
That'd be fine too - wasn't sure what all might have expected the project.Name field to be there, but if this is the only place for sure give it the boot.

**Comment by matyasselmeci** [comment]
The data structure should look the same but the value of the Name field should be taken from the filename instead of the Name line in the YAML.

**Comment by matyasselmeci** [comment]
I'm closing this since the proper solution is to get rid of the Name field.

**Pull request closed without merging**
