### PR TITLE
Adding BNL SDCC support center, contacts, site, resource group, resource

### PR DESCRIPTION
**Pull request by jhover**
Actually I went ahead and added a support group 'SDCC' and just left the ID blank. Maybe you can massage it into place? thx.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Hi John,
Could you create a `topology/Brookhaven National Laboratory/Scientific Data and Computing Center/SITE.yaml file`? There's a `template-SITE.yaml`.

**Comment by jhover** [comment]
Actually I did go ahead after all and make those (along with an edited 
/topogoy/support-centers.yaml file) and did a pull request.

But I didn't fill in some IDs (on the site, resource group, or support 
center) so I guess it will still need some editting on your end.

Let me know if I got it wrong.

Cheers,

--john

**Comment by matyasselmeci** [comment]
I don't see that file as part of this pull request, nor do I see any other pull requests with it. Did you forget to git add it perhaps?

**Comment by matyasselmeci** [comment]
Hi John,
I don't see the SITE.yaml file. Could you git add and commit it please?
Thanks,
-Mat

**Comment by edquist** [comment]
Hi @jhover, thanks for adding the `SITE.yaml`.

As for ID numbers, there are several scripts under the `bin` dir named `next_*_id` (eg, `next_support_center_id`) for generating IDs for different types of objects.  I've just gone ahead and added the missing ones to your PR.

**Pull request merged**
