### PR TITLE
new projects for ash khan

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by mwestphall** [comment]
@opensciencegrid/project-office resurfacing this, do we have approval to create the new organization "Northwestern Medicine"?

**Comment by jstathas** [comment]
Hi Matt,

Do you have an address or at least a City and State. for this org?

Janet


Janet Stathas (she/her)

Project Manager

Morgridge Institute for Research

PATh<https://path-cc.io/>

Email: ***@***.***

Mobile: 608.345.9605

________________________________

**Comment by brianhlin** [comment]
@jstathas I looked up the PI and it appears that she's based out of https://ror.org/04fzwnh64

**Comment by jstathas** [comment]
HI Brian,

Thanks - then "Northwestern Medicine" is approved.

Janet


Janet Stathas (she/her)

Project Manager

Morgridge Institute for Research

PATh<https://path-cc.io/>

Email: ***@***.***

Mobile: 608.345.9605

________________________________

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
