### PR TITLE
New project: UMBC_Nasipak

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by mwestphall** [comment]
Hi @rynge, is this institution the same as "University of Maryland, Baltimore" or different? The former exists already in our institutions list but the "Baltimore County" version doesn't.

**Comment by rynge** [comment]
It is different:

https://ror.org/02qskvh78
https://ror.org/04rq5mt64

Also confirmed by TimC.

**Comment by mwestphall** [comment]
Hi @opensciencegrid/project-office , are we good to add "University of Maryland, Baltimore County" as a topology institution?

**Comment by matyasselmeci** [comment]
Hi @opensciencegrid/project-office , can we get approval for the new organization "University of Maryland, Baltimore County" ?

**Comment by jstathas** [comment]
Matyas,

The source data clearly references Baltimore County? If yes, then approved. I just want to be sure that it should not be https://ror.org/04rq5mt64
________________________________
University of Maryland, Baltimore instead.

Janet


From: Matyas Selmeci ***@***.***>
Date: Tuesday, September 24, 2024 at 10:32 AM
To: opensciencegrid/topology ***@***.***>
Cc: Stathas, Janet ***@***.***>, Team mention ***@***.***>
Subject: Re: [opensciencegrid/topology] New project: UMBC_Nasipak (PR #4143)

Hi @opensciencegrid/project-office<https://github.com/orgs/opensciencegrid/teams/project-office> , can we get approval for the new organization "University of Maryland, Baltimore County" ?

**Comment by matyasselmeci** [comment]
Indeed it does. Thanks!

**Pull request merged**
