### PR TITLE
Updated topology for perfSONAR at UFL

### PR DESCRIPTION
**Pull request by ShawnMcKee**
I made two changes:
1) Added the new perfSONAR instance Bockjoo requested (IPv6 testing)
2) Fixed the topology to have one entry per perfSONAR host
Shawn

### CODE REVIEW

**Comment by brianhlin** [comment]
@matyasselmeci are spaces allowed in resource names?

**Comment by matyasselmeci** [comment]
We have at least one of those from existing data, so yes.

**Comment by matyasselmeci** [comment]
Shawn, these resources are marked as inactive ("Active: false") and disabled ("Disable: true"). Is that correct, or do you want to change that?

**Comment by ShawnMcKee** [comment]
Sure, I was just copying the original here but they shouldn't be marked
that way.  They should be "Active: true" and "Disable: false".

Do you need another pull request?

Thanks,

Shawn

**Comment by matyasselmeci** [comment]
I don't need another pull request; you can just add a commit to this one.

**Comment by brianhlin** [comment]
In the support ticket, it sounds like the new (?) perfsonar host isn't installed yet so `Active: False` may actually be what we want here. @ShawnMcKee does that sound correct? If so, then I think we just need to set `Disable: False` as well (@matyasselmeci I vaguely remember making `Disable: False` the default so we don't have to explicitly set it anymore)

**Comment by matyasselmeci** [comment]
Active: true and Disable: false are the defaults. We can set Active: false for now, but we'll need to remember to 1) update it when the new hosts are ready and 2) not have the new entries get wiped in our great purge #103

**Comment by ShawnMcKee** [comment]
Hi Brian,

This sounds right to me.  Bockjoo noted that the new host would be
installed "soon".

Shawn

**Comment by brianhlin** [comment]
@ShawnMcKee could you remove the `Disable: True` lines and set `Active: True` for any of the hosts that are currently up? Once that's done, we can get this merged into master. Then we can have Bockjoo flip the `Active` value when the new host is up

**Pull request merged**
