### PR TITLE
Register production Pelican cache for the CHTC (INF-1536)

### PR DESCRIPTION
**Pull request by williamnswanson**
Add the production pelican cache at `osdf-uw-cache.svc.osg-htc.org` as a CHTC resource.

### CODE REVIEW

**Comment by brianhlin** [comment]
@williamnswanson CI appears to be failing because it can't find you in our registered contacts: https://github.com/opensciencegrid/topology/actions/runs/7962628930/job/21736513751?pr=3657#step:8:35

I think that's because you need to give yourself the Topology Contact role

**Comment by williamnswanson** [comment]
Ok, I've added the Topology Contact role to myself.

**Comment by williamnswanson** [comment]
Test seems to be failing due to topology wanting my middle initial as well.

**Review by brianhlin — APPROVED** [review]
LGTM! Could you rebase on `master` and force push? That should satisfy the repo requirements and we can merge

**Pull request merged**
