### PR TITLE
adjust contact names to match comanage (SOFTWARE-5218)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
Of course, the checks are failing because the adjusted contact names match what is in comanage but not yet in the contact db until https://bitbucket.org/opensciencegrid/contact/pull-requests/348/adjust-contact-names-to-match-comanage is merged

**Comment by edquist** [comment]
force-pushed without changes (just an amended to bump the commit timestamp, to produce a new commit hash) to re-trigger the checks

**Comment by edquist** [comment]
Aaaand the checks pass.

**Review by brianhlin — APPROVED** [review]
LGTM!

> force-pushed without changes (just an amended to bump the commit timestamp, to produce a new commit hash) to re-trigger the checks, now that the contact PR is merged

FWIW, you can go to the checks tab in a PR or click the "see details" link in the failing test and there's a drop-down to re-run the failed jobs (or re-run all jobs)

**Comment by edquist** [comment]
Ah, thanks for the tip.  I looked a bit for something like that but apparently did not look hard enough!

**Pull request merged**
