### PR TITLE
Adding MISSOURI_RISE_NRP_OSDF_ORIGIN VO

### PR DESCRIPTION
**Pull request by biozit**
Adding MISSOURI_RISE_NRP_OSDF_ORIGIN VO

### CODE REVIEW

**Comment by brianhlin** [comment]
@biozit why do we need a separate VO for this origin?

**Review by brianhlin — CHANGES_REQUESTED** [review]
Throwing this into request changes so that it doesn't accidentally get merged without the VO justification

**Comment by brianhlin** [comment]
Discussed this with Fabio on Slack and he's going to update this PR to add the origin to the OSG VO

**Comment by matyasselmeci** [comment]
Do we still need this?

**Comment by biozit** [comment]
nop :-)

**Pull request closed without merging**
