### PR TITLE
move triton and prp into correct SDSC site dir

### PR DESCRIPTION
**Pull request by jdost321**
more cleanup action items from:
https://support.opensciencegrid.org/a/tickets/66930

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by brianhlin** [comment]
@jdost321 apparently GitHub won't let us handle the merge between your two branches in the UI. Could you update your `master` then merge it into the site migration branch?

**Comment by jdost321** [comment]
@brianhlin hopefully that fixed it?

**Comment by brianhlin** [comment]
Yup, looks good!

**Pull request merged**
