### PR TITLE
Create CMB_Petravick.yaml

### PR DESCRIPTION
**Pull request by rachellombardi**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Normally we go "Institution_PI" for the project name; we use "Illinois" as the prefix for "University of Illinois Urbana-Champaign".  Should this be Illinois_Petravick or is there a reason we're using CMB for this?

**Comment by rachellombardi** [comment]
This project name came about from this ticket: https://support.opensciencegrid.org/a/tickets/70228

In comanage, I've changed CMB to Illinois in the group name and all corresponding identifiers. The .yaml file name in this PR has also been updated.

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
OK, thanks!

**Comment by brianhlin** [comment]
@rachellombardi just checking, did any of these users submit jobs using the CMB group name? If there are accounting records associated with the old group name, we may have to add a compat symlink here so the accounting system is happy.

**Comment by rachellombardi** [comment]
@brianhlin yes, jobs have been submitted under CMB.

**Comment by brianhlin** [comment]
@rachellombardi Gotcha. The users will have to update their projects probably, right?

**Pull request merged**
