### PR TITLE
 Add downtime for AMNH due to Update

### PR DESCRIPTION
**Pull request by mmascher**

### CODE REVIEW

**Comment by mmascher** [comment]
Let me actually close this and try the automatic merge.

**Comment by mmascher** [comment]
Oh, Carl already merged it

**Comment by jdost321** [comment]
@mmascher  you broke the osg-bot's heart you should be ashamed :wink:

**Comment by edquist** [comment]
To be sure, osg-bot was imbued with feelings, despite his cold-looking metal exterior.

**Comment by mmascher** [comment]
LOL!

**Pull request merged**
