### PR TITLE
New top-level institution: Wichita State University; FD #78429

### PR DESCRIPTION
**Pull request by osg-cat**

### CODE REVIEW

**Comment by osg-cat** [comment]
Needs approval from Project Office.

**Comment by jstathas** [comment]
The ROR value  https://ror.org/00c4e7y75 is “Wichita State University” which is already in the campus database list.


From: Tim Cartwright ***@***.***>
Date: Wednesday, December 11, 2024 at 4:33 PM
To: opensciencegrid/topology ***@***.***>
Cc: Stathas, Janet ***@***.***>, Review requested ***@***.***>
Subject: Re: [opensciencegrid/topology] New top-level institution: Wichita State; FD #78429 (PR #4371)

@osg-cat<https://github.com/osg-cat> requested your review on: #4371<https://github.com/opensciencegrid/topology/pull/4371> New top-level institution: Wichita State; FD #78429.

**Comment by brianhlin** [comment]
Adjusted the PR title to reflect the actual changes, which appeared to actually match RoR + our own db

**Comment by osg-cat** [comment]
Sorry, I didn’t realize that the PR title was supposed to include the blessed/ROR institution name.

**Review by brianhlin — CHANGES_REQUESTED** [review]
@osg-cat it looks like I can't add a suggestion for an emtpy file. Can you fill in `FACILITY.yaml` with

```
---
InstitutionID: " https://osg-htc.org/iid/p3nn2sljiwwl"
```

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
