### PR TITLE
Update BNL-ATLAS.yaml

### PR DESCRIPTION
**Pull request by orind**
Updated DNS name for two compute elements that are being rebuilt gridgk0[7,8].racf.bnl.gov -> gridgk0[7,8].sdcc.bnl.gov

### CODE REVIEW

**Review by mwestphall — APPROVED** [review]

**Comment by bbockelm** [comment]
Note - this might cause issues with prior accounting data as the accounting data is based on hostname.

@djw8605 - any concerns?

**Comment by djw8605** [comment]
Indeed, this will impact prior accounting.  The ideal case is to keep the old dns entries, and make new resources with the new dns.

**Comment by glushkov** [comment]
Is there a CE retirement procedure in OSG? Or we have to keep in the site configuration all retired resources forever? Can we at least shorten the entry that is left behind to the bare minimum?

**Comment by bbockelm** [comment]
@glushkov - the preferred mechanism is:

1.  Add the new hostname as a separate CE in the same resource group.  That'll allow you to get accounting information to the WLCG, for example, from the new host.
2. Mark the old hostname as `Active: false`.  This indicates the CE is "retired".
3. After a year with no accounting information, we can remove the old CE from git.

We periodically re-compute the accounting numbers to allow late-arriving (or corrected) data to be reflected in the summaries.  The policy is we only recompute information less than a year old; at that point, things can be completely removed.

**Comment by brianhlin** [comment]
> Is there a CE retirement procedure in OSG?

@glushkov as Brian mentioned, the key to retiring a resource in Topology is setting `Active: false`. For future reference, that's documented here: https://osg-htc.org/docs/common/registration/#retiring-resources

**Pull request merged**
