### PR TITLE
Clean up Topology contact fields (SOFTWARE-4946)

### PR DESCRIPTION
**Pull request by RyanEweSeng**

### CODE REVIEW

**Comment by djw8605** [comment]
I 100% agree with any pull request that removes this many lines! (this is not a review)

**Comment by brianhlin** [comment]
@RyanEweSeng we're seeing a failure in the CI (https://github.com/opensciencegrid/topology/pull/2218/checks#step:6:18), which indicates that we have an empty `ContactLists:` somewhere (or maybe an empty `Administrative Contact:` or `Security Contact:`)

**Comment by RyanEweSeng** [comment]
Hey Brian I think there were cases where `Administrative Contact:` only contained the redundant contact fields listed so after removing the redundant fields, `Administrative Contact:` would be empty

**Comment by brianhlin** [comment]
@RyanEweSeng hrm, could you show an example of that?

**Review by brianhlin — APPROVED** [review]
LGTM!

**Pull request merged**
