### PR TITLE
Update UColorado_HEP for SQUID

### PR DESCRIPTION
**Pull request by doug1977**
This is the second attempt to enter the SQUIDs.

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @doug1977, let's continue to use https://github.com/opensciencegrid/topology/pull/665 since the formatting is closer to the [appropriate template](https://github.com/opensciencegrid/topology/blob/master/template-resourcegroup.yaml#L15-L108). We'd like to add some [backup contacts](https://github.com/opensciencegrid/topology/pull/665#issuecomment-500492577), is there someone we should be using for that?

**Comment by doug1977** [comment]
Hi Brian,
You can add any of the following for contacts:

    Kevin Stenson:  Kevin.Stenson@colorado.edu
    Keith Ulmer:      Keith.ulmer@colorado.edu
    John Cumalat:   john.p.cumalat@colorado.edu

Kevin Lannon would like to see this ticket closed as soon as possible. The
initial ticket was for SQUID registration which I think is close to
complete.

Thank you,
doug

**Comment by matyasselmeci** [comment]
Closing: fixed by #690.

**Comment by matyasselmeci** [comment]
We don't have those three people registered in our contact DB yet; we can do that and add them as backup contacts separately.

**Pull request closed without merging**
