### PR TITLE
Create SDSC-RDS.yaml

### PR DESCRIPTION
**Pull request by wmarkuske**
New resource group SDSC Research Data services. First resource is an OSDF data origin for XENON VO.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Hi @wmarkuske , what's the DN of this origin server? (The "subject" field of its SSL certificate.) It is required for XCache resources (caches and origins).

**Comment by wmarkuske** [comment]
rds-origin.sdsc.edu

**Comment by matyasselmeci** [comment]
I am looking for the full DN of the certificate. This should be a string that looks like `/CN=rds-origin.sdsc.edu` if the cert was issued by Let's Encrypt, or something like `/DC=org/DC=incommon/C=US/ST=CA/L=La Jolla/O=University of California, San Diego/OU=UCSD/CN=rds-origin.sdsc.edu` if it was issued by InCommon or some other traditional certificate authority.

For origins the certificate is typically stored at `/etc/grid-security/xrd/xrdcert.pem`; to display the subject you should run
```
openssl x509 -in /etc/grid-security/xrd/xrdcert.pem -noout -subject
```
note: newer versions of OpenSSL might print it like `DC = org, DC = incommon, C = US, ST = CA, L = La Jolla, O = University of California\, San Diego, OU = UCSD, CN = rds-origin.sdsc.edu` instead.

**Comment by wmarkuske** [comment]
Sorry I just blanked and just thought FQDN which is in the resource file. Below is the full DN. rds-origin.sdsc.edu is a CNAME for the current rds-origin-01.sdsc.edu and included as an alternate name in the certificate.

DC = org, DC = incommon, C = US, ST = California, O = "University of California, San Diego", OU = San Diego Supercomputer Center, CN = rds-origin-01.sdsc.edu

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
