### PR TITLE
Update SWT2_CPB_downtime.yaml

### PR DESCRIPTION
**Pull request by ptmcguigan**
Tried this last night, but I think I was not modify the correct trunk.  Trying again.

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi @ptmcguigan - I just corrected a small formatting issue.

To double-check: this is listed as being at 0700 GMT (i.e., 0100 central).  Is that correct?

**Comment by ptmcguigan** [comment]
HI,

Actually it is at 2am Sunday morning, which should be 07:00 GMT.

Patrick

**Comment by bbockelm** [comment]
Looks like a few downtimes are in the wrong files:

- Downtime for UTA_SWT2_perfSONAR_latency is in SWT2_CPB but should be in UTA_SWT2
- perfSONAR_SWT2_CPB_testbed_bandwidth is in SWT2_CPB but should be in SWT2_CPB_TEST
- perfSONAR_SWT2_CPB_testbed_latency is in SWT2_CPB but should be in SWT2_CPB_TEST.

Can you fix these?  Or would you prefer I take a whack at it?

**Comment by ptmcguigan** [comment]
Many thanks if you can rearrange them,

I am afraid that I would screw it up again.

Patrick

**Pull request merged**
