### PR TITLE
Update UNLCachingInfrastructure.yaml

### PR DESCRIPTION
**Pull request by biozit**
@djw8605 this is the only way I can create the certs from UCSD :-(

### CODE REVIEW

**Comment by djw8605** [comment]
I'm not super excited about this.  I would much rather put it under the opensciencegrid.org or osgstorage.org domains, just to keep it institutionally neutral.

But, if this is our only option, I'm ok with it.  At least we can change it in the future rather easily.

**Comment by biozit** [comment]
You said something about requesting certs from somewhere

**Comment by biozit** [comment]
certs installed

**Comment by biozit** [comment]
Will be the same with Massachusetts Green High Performance Computing Center

**Comment by bbockelm** [comment]
@biozit - should we be closing this PR?

**Comment by biozit** [comment]
yes, I do it.

**Pull request closed without merging**
