### PR TITLE
add Caltech LIGO Origin resource; Freshdesk #6671

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by edquist** [comment]
That uncaught CI failure is happening inside of `src/webapp/rg_reader.py`, and the traceback points to `src/webapp/topology.py`.  @matyasselmeci these are your scripts, if you'd like to decide how to handle a missing SupportCenter.

Anyway the latter CI tests shows

```
Resource Group 'California Institute of Technology/Caltech LIGO/CIT_LIGO.yaml' has no SupportCenter
```

which is the issue here.

**Comment by matyasselmeci** [comment]
I think a SupportCenter should be mandatory but it should certainly fail more gracefully than with a stack trace.

**Comment by zvada** [comment]
hey guys ... there is also bit of inconsistency whether `SupportCenter` or `SupportCenterName` ... and either `LIGO` or `Advanced LIGO`:
```
$ grep -R -i SupportCenter * | grep -i ligo
topology/University of Wisconsin Milwaukee/UW Milwaukee Physics/LIGO_UWM_NEMO.yaml:SupportCenter: LIGO
topology/California Institute of Technology/Caltech LIGO/CIT_LIGO.yaml:SupportCenterName: Advanced LIGO
topology/Georgia Institute of Technology/Georgia Tech/Georgia Tech LIGO.yaml:SupportCenter: Advanced LIGO
topology/Georgia Institute of Technology/Georgia Tech/Georgia Tech PACE.yaml:SupportCenter: Advanced LIGO
```
Both centers exist in `topology/support-centers.yaml`. I actually wasn't sure what to add initially so I omitted that line :), thus error... For this case, I think it should be `Advanced LIGO` as I see contact names that requested add this particular resources to the StashCache federation, but I wouldn't know otherwise.

**Comment by matyasselmeci** [comment]
How'd that get in there?

It should be SupportCenter, not SupportCenterName.

**Comment by edquist** [comment]
Hey @zvada, sorry for the confusion.  It's supposed to be just `SupportCenter`, but it looks like the confusion comes from `SupportCenterName` appearing in the template.  @matyasselmeci is fixing that.

**Comment by zvada** [comment]
Confusion comes from the template, actually:
```
$ grep -v \# template-resourcegroup.yaml | grep Support
SupportCenterName: <NAME>
```

**Comment by zvada** [comment]
Ah, our comments crossed, @edquist commented on that. Thanks!

**Comment by zvada** [comment]
ugh, this shouldn't fail so horribly @matyasselmeci if executing out of `bin` dir, right?
```
[zvada@hcc-marian topology]$ . bin/next_resource_group_id 
dirname: invalid option -- 'b'
Try 'dirname --help' for more information.
grep: topology/*/*/*.yaml: No such file or directory
1
Connection to hcc-marian.unl.edu closed.
```

Works fine when `cd bin`, though:
```
[zvada@hcc-marian bin]$ ./next_resource_group_id 
485
```

**Comment by matyasselmeci** [comment]
> `. bin/next_resource_group_id`
That looks like a typo. It should be either `./bin/next_resource_group_id` or just `bin/next_resource_group_id`.

**Comment by zvada** [comment]
you're right! was too fast to report something I did wrong on my end, sorry! All good, thanks.

**Comment by matyasselmeci** [comment]
Could you add an "ID" to the CIT_LIGO_ORIGIN resource, too? Get the number with `bin/next_resource_id`.

**Comment by brianhlin** [comment]
@edquist @matyasselmeci this looks ready for re-review

**Comment by edquist** [comment]
Travis is happy, nothing crazy-looking in the changeset, LGTM.

**Pull request merged**
