### PR TITLE
Adding bigger stars for CC* map

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by djw8605** [comment]
@matyasselmeci quick review please?

**Comment by matyasselmeci** [comment]
What's star.svg used for? I didn't see it in the template changes.

**Review by matyasselmeci — APPROVED** [review]

**Comment by matyasselmeci** [comment]
Looks good (other than my question about the SVG file); I'll deploy it tomorrow.

**Comment by djw8605** [comment]
The star.svg is the raw image, so that I can change the color, size, etc later.  I used inkscape, but I'm sure other apps can open and edit svg's.

**Comment by matyasselmeci** [comment]
Deployed on topology.

**Pull request merged**
