### PR TITLE
Tell people to run next_downtime_id

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Sites, facilities, RGs are easy to get the next ID for, but I can't think of a good way to get the next ID for a Resource using basic shell tools. @edquist or I might have to hack together a primitive Python YAML parser so a user can run the script without installing anything.

**Comment by matyasselmeci** [comment]
Or write it in Perl and use YAML::Tiny which is a single file and can be embedded into the script.

**Comment by edquist** [comment]
Discussed a bit with @matyasselmeci -

Seems "fine" (or, at least sufficient) to check for something like `^ +ID: +[0-9]{1,9} *$` - the main thing we are trying to avoid are the Contact IDs, which look like `^ +ID: [0-9a-f]{40}$`

**Comment by edquist** [comment]
Or `^ +ID: +[0-9]{1,6} *$`, if @matyasselmeci really wants to make sure we never exceed 999,999 historical resources.

**Pull request merged**
