### PR TITLE
Removing Compute Element until activated

### PR DESCRIPTION
**Pull request by ahkumar**
Removed CE as it has been decommissioned until new server is setup. 
Also removed SRM resource as we transitioned to Gridftp only Storage Element.

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Hi Amit,

Could you also remove the downtime info associated with that CE? It's in the file `topology/Southern Methodist University/SMU_HPC/SMU_HPC_downtime.yaml`. Just remove all the entries where `ResourceName` is `SMU_ManeFrame_CE`.

**Comment by ahkumar** [comment]
Just created a new pull request after updating downtime info, please let me know if I did it right?

**Comment by matyasselmeci** [comment]
Hi Amit,
It would have been easier if you had put the new commit in this PR. Unfortunately, you deleted a little too much -- the files are in YAML format so the record actually begins when the line starts with a `-` character. I merged them after a bit of fixing up.

I'll try to come up with some way of making the record boundaries more obvious; you were not the only person that ran into this problem.

**Comment by ahkumar** [comment]
Hi Mat, sorry about that I should have been careful as well. Please let me know if there is anything else I need to do from my end? Also where would I check that my resource is active on the OSG site?

**Pull request merged**
