### PR TITLE
Update UFlorida-HPC_downtime.yaml

### PR DESCRIPTION
**Pull request by bockjoo**
Network issue due to a switch that went bad

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @bockjoo,

The time's need to be in UTC (see [these errors](https://travis-ci.org/opensciencegrid/topology/builds/424850128#L628-L644)). Was the outage from Sep 3, 2018 9:00 EDT to Sep 3, 2018 11:15 EDT?

Thanks,
Brian

**Comment by bockjoo** [comment]
Yes. I added 'EDT' to the time format. I am afraid that offends the time format.
It should be from
Sep 3, 2018 05:00 to Sep 3, 2018 09:15
in UTC.
Thanks,
Bockjoo

**Comment by brianhlin** [comment]
@bockjoo did you mean that the downtime ended at 07:15 UTC? The original end time you submitted was 11:15 EDT.

**Comment by bockjoo** [comment]
Yes, it should be 07:15.

**Pull request merged**
