### PR TITLE
Update EndTime of permanent outages

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by brianhlin** [comment]
I'd prefer removing them outright, let's see what Alessandro says

**Comment by brianhlin** [comment]
@edquist can we handle the exceptions mat's seeing to get a more helpful failure message?

**Comment by matyasselmeci** [comment]
@edquist , this was due to an empty downtime file. You should check if the parsed YAML data is None and if so, add an error saying "$filename was not parseable" or something.

**Comment by edquist** [comment]
I've made #134 to make better errors in the future for empty yaml files.

**Pull request merged**
