### PR TITLE
Added new project: CSM_BeEST

### PR DESCRIPTION
**Pull request by rynge**

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Hi Mats,
Other Colorado School of Mines projects start with "Mines" instead of "CSM".
Sorry I haven't announced this, but I added a topology page with a list of organizations with their prefixes: https://topology.opensciencegrid.org/organizations

**Comment by rynge** [comment]
Yes, I'm aware of the naming convention, but this was created as part of the summer school and got into the system (GRACC and so on) before we could catch it.

**Comment by matyasselmeci** [comment]
OK. By the way, can you move the Utah commit into a separate branch? It's unrelated to this PR.

**Comment by rynge** [comment]
There you go

**Review by matyasselmeci — APPROVED** [review]

**Pull request merged**
