### PR TITLE
Add test to verify that XRootD caches have a DN attribute (SOFTWARE-3667)

### PR DESCRIPTION
**Pull request by brianhlin**
Additional commits on that ignores inactive caches, fixing #642

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Looks like it didn't catch one of them -- I see this in the warnings:
> `# WARNING: Resource UCSD_STASHCACHE_CACHE was skipped for VO HCC because the resource does not provide a DN.`

**Comment by brianhlin** [comment]
That's a separate test. I think you actually added that warning text to the authfile generation yourself :)

**Comment by matyasselmeci** [comment]
In https://github.com/opensciencegrid/docker-osg-build/blob/master/input/build-from-github#L10, you don't specify the mock config to use, so it uses the default mock config, which appears to be epel-7. So you don't have the osg repos available in the mock chroot. I'd suggest changing build-from-github to add `--mock-config-from-koji=osg-3.4-el7-build`. Read-only koji access should be sufficient for that, but you'll still have to run `osg-build setup` to put the right things into `~/.osg-koji`.

**Comment by matyasselmeci** [comment]
(We talked about this in person; it's OK for that one not to have a DN because it's inactive.)

**Pull request merged**
