### PR TITLE
Limit Issuer block titles to 50 characters (SOFTWARE-5659)

### PR DESCRIPTION
**Pull request by matyasselmeci**
Ensure the title of the 'Issuer' block is no more than 50 characters

- chop off the `https://` to give us a little more room
- use a sha1 hash if the title is still too big

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM. Though I thought this was fixed in XRootD?

**Comment by djw8605** [comment]
This is fixed in xrootd.  The new maximum is 1024 characters:
https://github.com/xrootd/xrootd/commit/c87bec48ca0162085942d70f6265975da8576a80

Looks like the fix has been in releases starting in 5.6.2

**Comment by matyasselmeci** [comment]
Yeah this is more for compat with earlier xrootd versions in case people need to downgrade because of an issue or something.

**Comment by brianhlin** [comment]
I think we should just abandon this and direct people to upgrade to 5.6.3 if they have any issues

**Comment by matyasselmeci** [comment]
Mmm. OK. I'm going to keep some of the test scaffolding because I'm using it in #3463; maybe split it out into a separate PR.

**Pull request closed without merging**
