### PR TITLE
Add Origin Information to Namespace Endpoint (SOFTWARE-5629)

### PR DESCRIPTION
**Pull request by CannonLock**
https://opensciencegrid.atlassian.net/browse/SOFTWARE-5629

### CODE REVIEW

**Comment by CannonLock** [comment]
Tested by sorting the results comparing the current and the new response to make sure the only thing changed was the addition of the origin information.

Resulting json files are zipped below. 

[Archive.zip](https://github.com/opensciencegrid/topology/files/12164761/Archive.zip)

**Comment by CannonLock** [comment]
Final changes. With a diff of the previous and the new result of this endpoint I can confirm this PR changes none of the current information, only adding origin lists to each namespace. 

[Archive 2.zip](https://github.com/opensciencegrid/topology/files/12173943/Archive.2.zip)

**Review by matyasselmeci — CHANGES_REQUESTED** [review]
`typing.Literal` was added in Python 3.8; scripts in `bin/` such as `osg-scitokens-config` might get run with Python 3.6 so we can't use any features from newer versions yet.

**Comment by CannonLock** [comment]
@matyasselmeci Ah, I remembered we got the webapp to 3.9 but makes sense others run this.

**Comment by CannonLock** [comment]
Sorry for the force pushes I misspelled "remot(v)e" and then proceeded to forget how to rebase.

**Review by matyasselmeci — APPROVED** [review]
LGTM

**Comment by matyasselmeci** [comment]
No worries, LGTM. Can you merge or rebase on master?

**Comment by matyasselmeci** [comment]
Once it's up to date, feel free to merge and deploy.

**Pull request merged**
