### PR TITLE
updating UCSDT2

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Comment by brianhlin** [comment]
@ddavila0 do you still want this to be a draft?

**Comment by djw8605** [comment]
APEL numbers look good to me.

**Comment by ddavila0** [comment]
I see that a validation has failed, seems that I need to get rid of all the Downtime records of UCSDT2-SE3 ? or should I instead do NOT remove the UCSDT2-SE3 resource and just mark it as Active=False ?

**Comment by brianhlin** [comment]
@ddavila0 I'd do the latter unless there's some other goal you have in removing the entire resource

**Review by brianhlin — APPROVED** [review]
Looks fine to me but I can't say anything about its correctness. If you notice any issues @jdost321 , we can submit another PR to fix them up

**Pull request merged**
