### PR TITLE
Compare cache configs via GHA cron (SOFTWARE-3470)

### PR DESCRIPTION
**Pull request by edquist**
Per discussion in SOFTWARE-3470, this is being moved here from https://github.com/cvmfs-contrib/config-repo/pull/117 .

The new script prints config diffs between topology's namespaces.json endpoint and the cvmfs-contrib/config-repo master branch, ignoring any items listed in the whitelist file.  Any differences will be reflected with exit status 1.

GHA cron added to run this hourly, to report failures without breaking other topology merges etc.
(Would some other interval like daily be more appropriate?)

"Aliases" via endpoint_override and auth_endpoint_override are ~not yet~ supported.

Sample script output:

```
Missing items from osgstorage.org.conf (to add)
 - fiona-r-uva.vlan7.uvalight.net:8000
 - hcc-stash.unl.edu:8000
 - helm-cache1.osgdev.chtc.io:8000
 - sc-cache.chtc.wisc.edu:8000
 - stash.farm.particle.cz:8000
 - stashcache.grid.uchicago.edu:8000
 - stashcache.gwave.ics.psu.edu:8000
 - stashcache.jinr.ru:8000
 - stashcache.uchicago.slateci.net:8000

Extra items in osgstorage.org.conf (to remove)
 - fiona.uvalight.net:8000

Missing items from ligo.osgstorage.org.conf (to add)
 - dtn2-daejeon.kreonet.net:8443
 - fiona-r-uva.vlan7.uvalight.net:8443
 - hcc-stash.unl.edu:8443
 - stashcache.gravity.cf.ac.uk:8443
 - stashcache.gwave.ics.psu.edu:8443
 - stashcache.t2.ucsd.edu:8443

Extra items in ligo.osgstorage.org.conf (to remove)
 - dtn2-daejeon.kreonet.net:8444
 - fiona.uvalight.net:8444
 - stashcache.gravity.cf.ac.uk:8444
 - stashcache.t2.ucsd.edu:8444
 - xrootd-local.unl.edu:1094

```

### CODE REVIEW

**Comment by djw8605** [comment]
When it says "to add", do you mean add to topology or add to the cvmfs-contrib repo?

**Comment by edquist** [comment]
>When it says "to add", do you mean add to topology or add to the cvmfs-contrib repo?

Ah, right.  To cvmfs-contrib/config-repo (where this script originally was envisioned to run).

But more specifically, when it says "to add" or "to remove", it means to/from the specific config file mentioned (which lives in cvmfs-contrib/config-repo) :

```
Extra items in osgstorage.org.conf (to remove)
Missing items from ligo.osgstorage.org.conf (to add)
```

**Comment by edquist** [comment]
@djw8605, if this is confusing, i'm open to suggestions for alternate phrasing...

**Comment by djw8605** [comment]
Something like:
"Caches in Topology, but missing from CVMFS configuration"

"Caches not in Topology, but in CVMFS configuration"

**Comment by edquist** [comment]
Ok updated, how does this look?

```
Caches in Topology, missing from CVMFS config osgstorage.org.conf
 - fiona-r-uva.vlan7.uvalight.net:8000
 - hcc-stash.unl.edu:8000
 - helm-cache1.osgdev.chtc.io:8000
 - sc-cache.chtc.wisc.edu:8000
 - stash.farm.particle.cz:8000
 - stashcache.grid.uchicago.edu:8000
 - stashcache.gwave.ics.psu.edu:8000
 - stashcache.jinr.ru:8000
 - stashcache.uchicago.slateci.net:8000

Caches in CVMFS config osgstorage.org.conf, missing from Topology
 - fiona.uvalight.net:8000

Caches in Topology, missing from CVMFS config ligo.osgstorage.org.conf
 - dtn2-daejeon.kreonet.net:8443
 - fiona-r-uva.vlan7.uvalight.net:8443
 - hcc-stash.unl.edu:8443
 - stashcache.gravity.cf.ac.uk:8443
 - stashcache.gwave.ics.psu.edu:8443
 - stashcache.t2.ucsd.edu:8443

Caches in CVMFS config ligo.osgstorage.org.conf, missing from Topology
 - dtn2-daejeon.kreonet.net:8444
 - fiona.uvalight.net:8444
 - stashcache.gravity.cf.ac.uk:8444
 - stashcache.t2.ucsd.edu:8444
 - xrootd-local.unl.edu:1094

```

**Comment by edquist** [comment]
Oh, and:

> "Aliases" via endpoint_override and auth_endpoint_override are not yet supported.

I think I had misunderstood this.  `endpoint` and `auth_endpoint` are [currently being used](https://github.com/opensciencegrid/topology/pull/2676/files#diff-149be6c73046486bc47655def38845f8b7fc3dd141c3fbbd65bd3ec625150e92R80-R81) from namespaces.json, which if i understand correctly are derived from fqdn + port for the resource by default, optionally overridden by `endpoint_override` and `auth_endpoint_override` if defined.  So I believe the current alias mechanism using `endpoint_override` and `auth_endpoint_override` is already implicitly supported.

**Review by brianhlin — APPROVED** [review]
@edquist This LGTM for a first pass but I think you'll need to revisit https://github.com/opensciencegrid/topology/pull/2676/files#diff-149be6c73046486bc47655def38845f8b7fc3dd141c3fbbd65bd3ec625150e92R106-R107 to take into the whitelist into account when we start adding to it.

Please update your branch via merge/rebase as you see fit then merge. I'd like to see the CI fail as expected with the existing diffs.

@djw8605 @matyasselmeci if we start doing OSPool auth caches, what's the plan for how they'll show up in the CVMFS config if at all? I ask because we're only looking at unauth caches here https://github.com/opensciencegrid/topology/pull/2676/files#diff-149be6c73046486bc47655def38845f8b7fc3dd141c3fbbd65bd3ec625150e92R98

**Comment by edquist** [comment]
> I think you'll need to revisit [this|https://github.com/opensciencegrid/topology/pull/2676/files#diff-149be6c73046486bc47655def38845f8b7fc3dd141c3fbbd65bd3ec625150e92R106-R107] to take into the whitelist into account when we start adding to it.

Ah yeah you're right, good catch.  It reports the whitelisted match correctly but the final exit status of the script does not account for the whitelisting.

**Comment by edquist** [comment]
@brianhlin I think I've fixed up the part you pointed out to account for the whitelist in 4e2e34c, feel free to give it a quick glance.

**Comment by edquist** [comment]
Look for a GHA cron run (to fail) in about 30 min.

**Comment by edquist** [comment]
@brianhlin, and all posterity, see failed run (right on schedule) run right here:

https://github.com/opensciencegrid/topology/actions/runs/3138263206/jobs/5097395217

**Pull request merged**
