### PR TITLE
Use a wrapper around yaml.safe_load

### PR DESCRIPTION
**Pull request by matyasselmeci**
(this time it works)

### CODE REVIEW

**Comment by matyasselmeci** [comment]
Yep. Tell you what, before you merge, I'll try killing that one too.

**Comment by matyasselmeci** [comment]
I find your comment disturbing. How sure are you that no resources were dropped?

**Comment by brianhlin** [comment]
Mat and I took this off-thread for a bit but to clarify my comment above, the ordering of resources in the resource dropdown of the downtime generation form were different for the facility that I spot checked (Arizona State University)

**Comment by matyasselmeci** [comment]
OK, the XMLs have the same number of elements (ran them through `xml2 <$XML | wc -l`) so I'm calling this good.

**Pull request merged**
