### PR TITLE
Create UNLNRPOrigin.yaml

### PR DESCRIPTION
**Pull request by biozit**

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
LGTM

**Review by djw8605 — CHANGES_REQUESTED** [review]
I take it back, wouldn't the hostname be something else?  some nrp-nautilus.io name?

**Comment by biozit** [comment]
Do you mean to change the hostname on the k8s cluster?

**Comment by djw8605** [comment]
No, I guess I'm just curious how it's going to be run.  I was under the impression it would run as a regular pod, just locked to either a node or a location.  Unlike the caches, there are a lot of nodes available to run this origin at each of the 3 locations.

**Comment by biozit** [comment]
The initial idea is to run on a specific node:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: nrpnborigin
  namespace: osg-services
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: nrpnborigin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nrpnborigin
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        env:
        - name: XC_RESOURCENAME
          value: nrpnborigin
        - name: ORIGIN_FQDN
          value: hcc-nrp-shor-c5832.unl.edu
        - name: XC_ROOTDIR
          value: /
        - name: XC_ORIGINEXPORT
          value: /nrpnb/
        image: opensciencegrid/stash-origin:3.6-testing-20220619-0738
        imagePullPolicy: Always
        name: nrpnborigin
        ports:
        - containerPort: 1094
          hostPort: 1094
          protocol: TCP
        - containerPort: 1095
          hostPort: 1095
          protocol: TCP
        - containerPort: 8444
          hostPort: 8444
          protocol: TCP
        - containerPort: 8445
          hostPort: 8445
          protocol: TCP
        - containerPort: 8443
          hostPort: 8443
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "2"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: hcc-nrp-shor-c5832.unl.edu
      restartPolicy: Always
```

**Comment by biozit** [comment]
@djw8605 is that ok?

**Comment by biozit** [comment]
The POD is ready with access to the storage.

**Comment by biozit** [comment]
The POD is mounting the Storage. How should we request the certs?

**Comment by biozit** [comment]
@bbockelm Can you check the VO?

**Review by matyasselmeci — APPROVED** [review]

**Review by djw8605 — APPROVED** [review]
LGTM

**Pull request merged**
