### PR TITLE
adding new university of nevada folks

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
@ChristinaLK @matyasselmeci @edquist we need to rope in @jstathas and @ilandrum before merging any new facilities or project institutions!

**Comment by brianhlin** [comment]
Our friendly osg-bot will drop a comment in the PR noting if it's an institution that we haven't seen before in a project https://github.com/opensciencegrid/topology/pull/2654#pullrequestreview-1097802473

**Comment by matyasselmeci** [comment]
Should we have osg-bot ping them automatically?

**Comment by brianhlin** [comment]
> Should we have osg-bot ping them automatically?

Yeah, I was thinking something along those lines. I think it's completely possible to do it entirely in GHA, though, which could be nice.

**Comment by ilandrum** [comment]
I have reviewed the request and see no issue at this time with the request for adding Kent State

**Pull request merged**
