### PR TITLE
Scheduled downtime for site network upgrades

### PR DESCRIPTION
**Pull request by jpata**
We are having a full site 24h downtime as planned for network upgrades. More details here (internal): https://caltech.teamwork.com/#tasks/13978962

@juztas @shashwithap @andres-moya

### CODE REVIEW

**Comment by edquist** [comment]
Here's the error:
```
California Institute of Technology/Caltech CMS Tier2/CIT_CMS_T2_downtime.yaml:
  ID: 223551490
  ResourceName: CIT_CMS_T2_HPC_Squid
  Resource 'CIT_CMS_T2_HPC_Squid' not found in resource group file
```

**Comment by matyasselmeci** [comment]
Yep. @jpata, you need to move the downtime for CIT_CMS_T2_HPC_Squid into CIT_CMS_T2_HPC_downtime.yaml.

**Comment by matyasselmeci** [comment]
I'll fix it for you.

**Comment by jpata** [comment]
thanks @matyasselmeci, sorry about that!

**Pull request merged**
