### PR TITLE
Adding FDP origin

### PR DESCRIPTION
**Pull request by biozit**
Adding FDP origin

### CODE REVIEW

**Comment by biozit** [comment]
@brianhlin, who should I add to the review to validate the institution name?

**Review by matyasselmeci — APPROVED** [review]

**Comment by bbockelm** [comment]
@jstathas / @matyasselmeci - who approved this new `DIII-D` facility name?

**Comment by jstathas** [comment]
Brian – I did not approve it nor did I receive a request to do so.


Janet

From: Brian P Bockelman ***@***.***>
Date: Wednesday, June 5, 2024 at 5:26 PM
To: opensciencegrid/topology ***@***.***>
Cc: Stathas, Janet ***@***.***>, Mention ***@***.***>
Subject: Re: [opensciencegrid/topology] Adding FDP origin (PR #3919)

@jstathas<https://github.com/jstathas> / @matyasselmeci<https://github.com/matyasselmeci> - who approved this new DIII-D facility name?

**Comment by bbockelm** [comment]
@biozit -- can you please open a new ticket in this case?  DIII-D is not a facility.

**Comment by biozit** [comment]
https://support.opensciencegrid.org/a/tickets/76681

**Review by jstathas — COMMENTED** [review]
DIII-D National Fusion Facility is approved

https://ror.org/04zptmf07

**Comment by bbockelm** [comment]
Great!

@biozit - can you open a new PR renaming the facility to "DIII-D National Fusion Facility"?

**Comment by biozit** [comment]
https://github.com/opensciencegrid/topology/pull/3957/commits

**Pull request merged**
